// client/client-angular/src/app/shared/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { UserInfo } from 'src/app/service/user-info.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {
  public isUserAuth: boolean;
  public userRole;
  constructor(
    private userInfo: UserInfo
    ) {
      // Return true if user have token from the server in another case return false
      this.isUserAuth = this.userInfo.isUserAuth();

      // Return true if user have status Admin
      this.userRole = this.userInfo.getStatus();
    }

  ngOnInit() {
  }

}

<nav class="col s12">
  <div class="nav-wrapper teal">
    <a routerLink="/" class="brand-logo"> Logo</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li *ngIf="isUserAuth">
        <a 
        routerLink=""
        routerLinkActive="active-link"
        [routerLinkActiveOptions]="{exact: true}"
        >Home</a>
      </li>
      <li *ngIf="isUserAuth">
        <a 
        routerLink="catalog"
        routerLinkActive="active-link"
        >GoogleBook</a>
      </li>
      <li *ngIf="isUserAuth">
        <a
        routerLink="gbooks"
        routerLinkActive="active-link"
        >Books</a>
      </li>
      <li *ngIf="(isUserAuth && userRole)">
        <a routerLink="user-manager"
        routerLinkActive="active-link"
        >Users</a>
      </li>
      <li *ngIf="!isUserAuth">
        <a
        routerLink="auth"
        >Log in</a>
      </li>
      <li class="dropdown"
      *ngIf="(isUserAuth)"
      >
        <a class="btn-floating btn-large  waves-effect waves-light teal">
          <img src="https://cdn.dribbble.com/users/219762/screenshots/2351573/saitama.png" alt="user avatar">
        </a>
        <ul>
          <li>
            <a
            routerLink="profile"
            routerLinkActive="active-link"
            [routerLinkActiveOptions]="{exact: true}"
            >My profile</a>
          </li>
          <li>
            <a
            routerLink="profile/favorites"
            routerLinkActive="active-link"
            >My favorites</a></li>
          <li *ngIf="!isUserAuth">
            <a
            routerLink="auth/login"
            routerLinkActive="active-link"
            >Log in</a>
          </li>
          <li *ngIf="isUserAuth" (click)="this.userInfo.logout()">
            <a
            routerLink="auth/login"
            routerLinkActive="active-link"
            >Log out</a>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</nav>

// client/client-react/src/shared/HeaderComponent/headerComponent.tsx
import React from 'react';
import { Link } from 'react-router-dom';
import './style.scss'
import { UserInfoService } from '../../service/user-info.service';
// const Header: React.FC = () => {
//   return (

//   );
// }

export default function Header() {
  const userInfoService = new UserInfoService();

  return (
    <nav className="col s12">
      <div className="nav-wrapper teal">
        <Link className="brand-logo" to="/">Logo</Link>
        <ul id="nav-mobile" className="right hide-on-med-and-down" //*ngIf="isUserAuth()"
        >
          <li><Link to='/'>Home</Link></li>
          <li>
            <Link to="/catalog">GoogleBook</Link>
          </li>
          <li>
            <Link to="/book-manager">Books</Link>
          </li>
          <li //*ngIf="userRole()">
          >
            <Link to="/user-manager">Users</Link>
          </li>
          <li className="dropdown">
            <Link className="btn-floating btn-large  waves-effect waves-light teal" to="/profile">
              <img src="https://cdn.dribbble.com/users/219762/screenshots/2351573/saitama.png" alt="user avatar"></img>
            </Link>
            <ul>
              <li>
                  <Link to="/profile">My profile</Link>
              </li>
              <li>
                <Link to="/profile/favorites">My favorites</Link>
              </li>
              <li onClick={userInfoService.logout}>
                <Link to="/auth/login">Log out</Link>
              </li>
            </ul>
          </li>
        </ul>
        <ul id="nav-mobile" className="right hide-on-med-and-down"  // *ngIf="!isUserAuth()"
        >
          <li>
            <Link to="/auth">Log in</Link>
          </li>
        </ul>
      </div>
    </nav>
  )
}
