// client/client-angular/src/app/shared/filter/filter.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { BookService } from 'src/app/service/books.service';
import { CategoryAuthor } from 'src/app/models/category-author.model';
import { ActivatedRoute } from '@angular/router';
import { Subject } from 'rxjs';
import { debounceTime } from 'rxjs/operators';

@Component({
  selector: 'app-filter',
  templateUrl: './filter.component.html',
  styleUrls: ['./filter.component.scss']
})
export class FilterComponent implements OnInit {
  @Input() getFilteredBooks: (data) => void;
  @Input() getAllBooks: () => void;

  public authors: CategoryAuthor[];
  public categories: CategoryAuthor[];
  public filterData = {
    title: '',
    categories: new Set(),
    authors: new Set()
  };
  public searchField = '';
  public searchStringUpdate = new Subject<string>();
  public linkParams;

  constructor(
    private bookService: BookService,
    private activeRoute: ActivatedRoute,
  ) {
    this.bookService = new BookService();
    this.searchStringUpdate
      .pipe(debounceTime(500))
      .subscribe(value => {
        console.log(value);
        this.filtering();
      });
  }

  ngOnInit() {
    this.linkParams = this.activeRoute.snapshot.queryParams;
    this.searchField = this.linkParams.title;
    this.getAuthors();
    this.getCategories();
  }

  public getAuthors(): void {
    this.bookService.getAllAuthors()
      .then((authors: CategoryAuthor[]) => {
        this.authors = authors.map(author => {
          return {
            ...author,
            checked: this.linkParams.hasOwnProperty('authors') ?
              this.linkParams.authors.indexOf(author._id) === -1 ? false : true
              : false
          };
        });
      });
  }

  public getCategories(): void {
    this.bookService.getAllCategories()
      .then((categories: CategoryAuthor[]) => {
        this.categories = categories.map(category => {
          return {
            ...category,
            checked: this.linkParams.hasOwnProperty('categories') ?
              this.linkParams.categories.indexOf(category._id) === -1 ? false : true
              : false
          };
        });
      });
  }

  public filtering(catauth?: CategoryAuthor): void {
    if (catauth !== undefined) {
      catauth.checked = !catauth.checked;
    }
    const data = {
      title: this.searchField,
      categories: [],
      authors: []
    };

    data.categories = this.categories.filter((obj) => {
      return obj.checked;
    }).map(obj => {
      return obj._id;
    });

    data.authors = this.authors.filter((obj) => {
      return obj.checked;
    }).map(obj => {
      return obj._id;
    });

    this.getFilteredBooks(data);
  }
}

<div class="col s2 filters">
  <div class="input-field">
    <input type="text" id="searchField"
      [(ngModel)]="this.searchField"
      (ngModelChange)="this.searchStringUpdate.next($event)"
    >
    <label for="searchField"
    [ngClass]="{active: this.searchField}"      
    >Search Field</label>
  </div>
  <div class="category-input" *ngFor="let category of categories">
    <input type="checkbox" id={{category._id}} [checked]="category.checked" (change)="filtering(category)"/>
    <label for={{category._id}}>{{category.name}}</label>
  </div>
  <hr>
  <div class="author-input" *ngFor="let author of authors">
    <input type="checkbox" id={{author._id}} [(checked)]="author.checked" (change)="filtering(author)"/>
    <label for={{author._id}}>{{author.name}}</label>
  </div>
  <hr>
</div>

// client/client-react/src/shared/filter/filter.tsx
import React from 'react'

export class Filter extends React.Component {

  render() {
    return (
      <div className="col s2 filters">
        <div className="input-field">
          {/* // [(ngModel)]="this.searchField"
          // (ngModelChange)="this.searchStringUpdate.next($event)" */}
          <input type="text" id="searchField" />
          <label //for="searchField"
          // [ngClass]="{active: this.searchField}"      
          >Search Field</label>
        </div>
        <div className="category-input" //*ngFor="let category of categories"
        >
          <input type="checkbox" id={category._id}// [checked]="category.checked" (change)="filtering(category)"/
          />
          <label //for={category._id}
          >{category.name}</label>
        </div>
        <hr/>
        {/* *ngFor="let author of authors" */}
        {/*  // [(checked)]="author.checked" (change)="filtering(author)"/ */}
        <div className="author-input">
          <input type="checkbox" id={author._id} />
          <label //for={author._id}
          >{author.name}</label>
        </div>
        <hr/>
      </div>
    )
  }
}
