// client/client-angular/src/app/shared/filter/filter.component.ts
import { Component, OnInit, Input, AfterViewInit } from '@angular/core';
import { BookService } from 'src/app/service/books.service';
import { CategoryAuthor } from 'src/app/models/category-author.model';
import { ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-filter',
  templateUrl: './filter.component.html',
  styleUrls: ['./filter.component.scss']
})
export class FilterComponent implements OnInit {
  @Input() getFilteredBooks: (data) => void;
  @Input() getAllBooks: () => void;

  public authors: CategoryAuthor[];
  public categories: CategoryAuthor[];
  public filterData = {
    title: '',
    categories: new Set(),
    authors: new Set()
  };
  public searchField = '';

  public linkParams;

  constructor(
    private bookService: BookService,
    private activeRoute: ActivatedRoute,
  ) {
    this.bookService = new BookService();
  }

  ngOnInit() {
    this.linkParams = this.activeRoute.snapshot.queryParams;
    this.getAuthors();
    this.getCategories();
  }

  public getAuthors(): void {
    this.bookService.getAllAuthors()
      .then((author: CategoryAuthor[]) => {
        this.authors = author.map(author =>{
          return {
            ...author,
            checked: this.linkParams.hasOwnProperty('authors') ?
              this.linkParams.authors.indexOf(author._id) === -1 ? false : true
              : false
          }
        });
      })
  }

  public getCategories(): void {
    this.bookService.getAllCategories()
      .then((categories: CategoryAuthor[]) => {
        this.categories = categories.map(category => {
          return {
            ...category,
            checked: this.linkParams.hasOwnProperty('categories') ?
              this.linkParams.categories.indexOf(category._id) === -1 ? false : true
              : false
          }
        });
      });
  }

  public filtering(): void {
    const data = {
      title: this.searchField,
      categories: [],
      authors: []
    };

    data.categories = this.categories.filter((obj) => {
      return obj.checked;
    }).map(obj => {
      return obj._id;
    })

    data.authors = this.authors.filter((obj) => {
      return obj.checked;
    }).map(obj => {
      return obj._id;
    })

    if (data.title.length === 0 && data.categories.length === 0 && data.authors.length === 0) {
      this.getAllBooks();
    } else {
      this.getFilteredBooks(data);
    }
  }
}

<div class="col s2 filters">
  <div class="input-field">
    <input type="text" id="searchField"
      [(ngModel)]="this.searchField"
    >
    <label for="searchField"
    [ngClass]="{active: this.searchField}"      
    >Search Field</label>
  </div>
  <div class="category-input" *ngFor="let category of categories">
    <input type="checkbox" id={{category._id}} [checked]="category.checked" (change)="category.checked = !category.checked"/>
    <label for={{category._id}}>{{category.name}}</label>
  </div>
  <hr>
  <div class="author-input" *ngFor="let author of authors">
    <input type="checkbox" id={{author._id}} [(checked)]="author.checked" (change)="author.checked = !author.checked"/>
    <label for={{author._id}}>{{author.name}}</label>
  </div>
  <hr>
  <button class="btn" (click)="filtering()">OK</button>
</div>

// client/client-react/src/shared/filter/index.tsx
import React, { Props } from 'react'
import { BookService } from '../../service/books.service';
import { CategoryAuthor } from '../../models/category-author.model';
import './style.scss'

export default class Filter extends React.Component {
  constructor(props: Props<any>) {
    super(props);
    this.bookService = new BookService();

    this.state = {
      categories: [],
      authors: []
    }

    this.bookService.getAllAuthors()
    .then(listOfAuthors => {
      this.setState({
        ...this.state,
        authors: listOfAuthors
      })
    });
    this.bookService.getAllCategories()
    .then(listOfCategories => {
      this.setState({
        ...this.state,
        categories: listOfCategories
      })
    });
  }

  public bookService: BookService;

  render() {
    return (
      <div className="col s2 filters">
        <div className="input-field">
          <input type="text" id="searchField" />
          <label>Search Field</label>
        </div>
        {
          (this.state as any).categories.map((category: CategoryAuthor, index: number) => {
            return (
              <label key={index}>
                <input type="checkbox"/>
                <span>{category.name}</span>
              </label>
            )
          })
        }
        <hr/>
        {
          (this.state as any).authors.map((author: CategoryAuthor, index: number) => {
            return (
              <label key={index}>
                <input type="checkbox" />
                <span>{author.name}</span>
              </label>
            )
          })
        }
        <hr/>
      </div>
    )
  }
}
