// client/client-react/src/shared/UserComponent/UserDeleteModal/index.tsx
import React, { Props } from 'react';
import './style.scss'

interface props {
  show: boolean;
  onClose: () => void;
  userEmail: string;
}

export class UserDeleteModal extends React.Component<props> {
  constructor(props: props) {
    super(props);
  }

  render() {
    if(!this.props.show) {
      return null;
    }

    return (
      <div className="mybackdrop">
        <div className="mymodal">
        <h3>Delete user?</h3>
          <p>Delete user with e-mail: <b>{this.props.userEmail}</b></p>
          
          <div className="myfooter">
            <button className="btn green"
              onClick={(this.props as any).onClose}
            >
              Cancel
            </button>
            <button className="btn red">
              Delete
            </button>
          </div>
        </div>
      </div>
    );
  }
}

// client/client-angular/src/app/admin/user-manager/user-delete-modal/user-delete-modal.component.ts
import { Component, Inject } from '@angular/core';
import { MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog';

@Component({
  selector: 'app-user-delete-modal',
  templateUrl: './user-delete-modal.component.html',
  styleUrls: ['./user-delete-modal.component.scss']
})
export class UserDeleteModalComponent {

  constructor(
    public confirmDialog: MatDialogRef<UserDeleteModalComponent>,
    @Inject(MAT_DIALOG_DATA) public data: {
      userId: string,
      userEmail: string,
      deleteFunc: (userId: string) => void
    }
  ) {}

  public cancel(): void {
    this.confirmDialog.close();
  }

  public delete(): void {
    this.data.deleteFunc(this.data.userId);
    this.confirmDialog.close();
  }

  public onNoClick(): void {
    this.confirmDialog.close();
  }
}

<h3>Delete user?</h3>
<p>Delete user with e-mail: <b>{{this.data.userEmail}}</b></p>
<button class="btn green"
  (click)="cancel()"
>
  Cancel
</button>
<button class="btn red"
  (click)="delete()"
>
  Delete
</button>
