// client/client-react/src/Admin/UserManager/UserManager.js
import React from 'react';

class UserManager extends React.Component {
  render() {
    return (
      <div className="row">
          <div className="col s8">
            <div className="card horizontal z-depth-4" 
            // *ngFor="let user of users"
            >`
              <div className="card-image col s4">
                <img src="{{user.image || 'https://cdn.dribbble.com/users/219762/screenshots/2351573/saitama.png'}}" className="user-image" alt="user`s img"/>
                <button 
                // (click)="selectUser(user)"
                className="btn edite-btn rework-btn">
                    <i className="material-icons">edite</i>
                </button>
                <button 
                // (click)="deleteUser(user._id)"
                className="btn delete-btn rework-btn">
                    <i className="material-icons">delete</i>
                </button>
              </div>
              <div className="card-stacked col s8">
                <div className="card-content">
                  <div className="card-title">
                    <b>user.name</b>
                    <br/>
                    <span><small>(user.role === 1) ? 'admin' : 'user'</small></span>
                  </div>
                  <p><b>E-mail: </b>user.email</p>
                  <ul> 
                    <span><b>List of books:</b></span>
                    <li 
                    // *ngFor="let book of user.book_list"
                    >book.title</li>
                  </ul>
                </div>
              </div>
              </div>
          </div>  
          <form className="col s4"
          //  [formGroup]="form" (ngSubmit)="onSubmit()"
          >
            <hr/>
            <div className="input-field">
              <input type="text" id="name" 
              // [(ngModel)]='userForEdite.name'
              // formControlName='name'
              />
              <label htmlFor="name" 
              // [ngClass]="{active: userForEdite.name}"
              >Name</label>
            </div>
            <div className="input-field">
              <input type="text" id="email" 
              // [(ngModel)]="userForEdite.email"
              // formControlName='email'
              />
              <label htmlFor="email" 
              // [ngClass]="{active: userForEdite.email}"
              >E-mail</label>
            </div>
            {/* // <!-- <div className="input-field">
            //     <input type="text" id="password" 
            //      [(ngModel)]="userForEdite.password"
            //     // formControlName='password'
            //     >
            //     <label for="password" [ngClass]="{active: userForEdite.password}">Password</label>
            // </div> --> */}
            <div className="input-field">
              <input type="number" id="role" 
              min="1"
              max="2"
              // [(ngModel)]="userForEdite.role"
              // formControlName='role'
              />
              <label htmlFor="role" 
              // [ngClass]="{active: userForEdite.role}"
              >Role</label>
            </div>
            <div className="input-field">
              <input type="text" id="id"
              //  [(ngModel)]="userForEdite._id" [ngModelOptions]="{standalone: true}"
              />
              <label htmlFor="id"
              //  [ngClass]="{active: userForEdite._id}"
              >id</label>
            </div>
            <div className="input-field">
              <input type="file" id="image"
              //  [(ngModel)]="userForEdite.image" [ngModelOptions]="{standalone: true}"
              />
              <label htmlFor="image">Image</label>
            </div>
            <div className="container center">
              <button type="button" className="btn waves-effect" 
                // (click)="addAction()" *ngIf="!okBtnStatus"
                // [disabled]="form.invalid"
                >Add
              </button>
              <button type="button" className="btn waves-effect" 
                // (click)="okAction()" *ngIf="okBtnStatus"
                // [disabled]="form.invalid"
                >OK
              </button>
            </div>
          </form>
      </div>
    )
  }
}

export default UserManager;

// client/client-angular/src/app/components/user-manager/user-manager.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { UserService } from '../../services/users.service';
import { UserFormAddEditeModalComponent } from './user-forms-add-edite-modal/user-forms-add-edite-modal.component';
import { MatDialog } from '@angular/material/dialog';
import { UserDeleteModalComponent } from './user-delete-modal/user-delete-modal.component';
import { User } from '../../models/user.model';
import { Subject } from 'rxjs';
import { debounceTime } from 'rxjs/operators';
import { PaginationEvent } from 'src/app/models/pagination-event.model';

@Component({
  selector: 'app-user-manager',
  templateUrl: './user-manager.component.html',
  styleUrls: ['./user-manager.component.scss']
})
export class UserManagerComponent implements OnInit {
  public users: object[];
  public searchString: string;
  public onSearchStringChange: Subject<string>;
  public paginationParams: PaginationEvent;

  constructor(
    private userService: UserService,
    public dialog: MatDialog
  ) {
    this.onSearchStringChange = new Subject<string>();
    this.onSearchStringChange
      .pipe(debounceTime(500))
      .subscribe(value => {
        this.userSearch();
      });

    this.paginationParams = {
        pageIndex: 0,
        pageSize: 5,
        previousPageIndex: 0,
        length: 0
      };
   }

  ngOnInit(): void {
    this.init();
  }

  public init(): void {
    this.userService.getAllUsers(this.paginationParams)
    .then(data => {
      this.users = data[0].listOfItem;
      this.paginationParams.length = data[0].totalCount[0].count;
    });
  }

  public deleteUser(id: string): void {
    this.userService.delete(id)
    .then(() => {
      this.init();
    });
  }

  public openDialog(user: User): void {
    const dialogRef = this.dialog.open(UserFormAddEditeModalComponent, {
      data: {
        user,
        reloadPage:  this.init.bind(this)
      }
    });
  }

  public confirmDialog(userId: string, userEmail: string): void {
    const confirmDialog = this.dialog.open(UserDeleteModalComponent, {
      data: {
        userId,
        userEmail,
        deleteFunc: this.deleteUser.bind(this)
      }
    });
  }

  public userSearch(pagination: PaginationEvent = {pageSize: this.paginationParams.pageSize, pageIndex: 0 }): void {
    this.userService.getSomeUsers(this.searchString, pagination)
    .then(data => {
      if (data[0].listOfItem.length) {
        this.users = data[0].listOfItem;
        this.paginationParams.length = data[0].totalCount[0].count;
      } else {
        alert('User not found');
      }
    });
  }

 public paginationHandler(pageEvent: PaginationEvent): PaginationEvent {
    if (this.searchString && this.searchString.length) {
      this.userSearch(pageEvent);
      return pageEvent;
    }
    this.paginationParams = pageEvent;
    this.init();
    return pageEvent;
  }
}

<div class="container">
    <div class="input-field center">
        <input type="text" name="searchField" [(ngModel)]="searchString" (ngModelChange)="this.onSearchStringChange.next($event)">
        <label for="searchField"
        [ngClass]="{active: searchString}"
        >Enter e-mail</label>
        <br>
    </div>
</div>
<div class="row">
    <div class="col s8 offset-s2">
        <div class="card horizontal z-depth-4" *ngFor="let user of users">
            <div class="card-image col s4">
                <img src="{{user.image || 'https://cdn.dribbble.com/users/219762/screenshots/2351573/saitama.png'}}" class="user-image">
                <button 
                (click)="openDialog(user)"
                class="btn edite-btn rework-btn">
                    <i class="material-icons">edite</i>
                </button>
                <button 
                (click)="confirmDialog(user._id, user.email)"
                class="btn delete-btn rework-btn">
                    <i class="material-icons">delete</i>
                </button>
            </div>
            <div class="card-stacked col s8">
                <div class="card-content">
                    <div class="card-title">
                        <b>{{user.name}}</b>
                        <br>
                        <span><small>({{(user.role === 1) ? 'admin' : 'user'}})</small></span>
                    </div>
                    <p><b>E-mail: </b>{{user.email}}</p>
                    <ul> 
                        <span><b>List of books:</b></span>
                        <li *ngFor="let book of user.book_list">{{book.title}}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container center">
    <button class="btn orange center" (click)="openDialog()">Add new user</button>
</div>
<mat-paginator 
    [length] = "paginationParams.length"
    [pageSize] = "paginationParams.pageSize"
    [pageSizeOptions] = "[3, 5, 7, 10, 25, 50]"
    (page) = "paginationHandler($event)">
</mat-paginator>
<app-modal></app-modal>
