// client/client-angular/src/app/components/favorites/favorites.component.ts
import { Component, OnInit } from '@angular/core';
import { UserInfo } from 'src/app/services/user-info.service';
import { UserService } from 'src/app/services/users.service';
import { Book } from 'src/app/models/book.model';
import {MatDialog} from '@angular/material/dialog';
import { FavoritesModalComponent } from './favorites-modal/favorites-modal.component';
import { User } from 'src/app/models/user.model';
import { FavoritesDeleteModalComponent } from './favorite-delete-modal/favorites-delete-modal.component';
import { Subject } from 'rxjs';
import { debounceTime } from 'rxjs/operators';
import { PaginationEvent } from 'src/app/models/pagination-event.model';

@Component({
  selector: 'app-favorites',
  templateUrl: './favorites.component.html',
  styleUrls: ['./favorites.component.scss']
})
export class FavoritesComponent implements OnInit {
  public books: Book[] = [];
  public user: User;
  public pageOfItems: Book[];
  public searchField: string;
  public onSearchFieldChange: Subject<string>;
  public paginationParams: PaginationEvent = {
    pageIndex: 0,
    pageSize: 5,
    previousPageIndex: 0,
    length: 0
  };

  constructor(
    private userInfo: UserInfo,
    private userService: UserService,
    public dialog: MatDialog
  ) {
    this.onSearchFieldChange = new Subject<string>();
    this.onSearchFieldChange
      .pipe(debounceTime(500))
      .subscribe(value => {
        this.searchFromFavorites();
      });
  }

  ngOnInit() {
    this.userService.getUser(this.userInfo.getCurrentUser().id)
    .then((user: User) => {
      this.user = user;
      if (user.books.length > 0) {
        this.userService.getUserBooks(user.books as string[], this.paginationParams)
        .then(data => { // make response type
          this.books = data[0].listOfItem;
          this.paginationParams.length = data[0].totalCount[0].count;
        });
      }
      if (user.books.length === 0) {
        this.books = [];
      }
    });
  }

  public paginationHandler(pageEvent: PaginationEvent): PaginationEvent {
    this.paginationParams = pageEvent;
    if (this.searchField && this.searchField.length) {
      this.searchFromFavorites();
      return pageEvent;
    }
    this.ngOnInit();
    return pageEvent;
  }

  public openDialog(book: Book): void {
    this.dialog.open(FavoritesModalComponent, {
      data: {
        book
      }
    });
  }

  public deleteDialog(book: Book): void {
   this.dialog.open(FavoritesDeleteModalComponent, {
      data: {
        book,
        allBooks: this.books,
        user: this.user,
        delete: this.deleteBookFromFavorite.bind(this)
      }
    });
  }

  public deleteBookFromFavorite(user: User): void {
    this.userService.edit(this.user._id, user)
    .then(() => {
      this.ngOnInit();
    });
  }

  public searchFromFavorites(): void {
    this.userService.getUser(this.userInfo.getCurrentUser().id)
    .then((user: User) => {
      this.user = user;
      if (user.books.length > 0) {
        this.userService.getUserBooks(user.books as string[], this.paginationParams, this.searchField)
        .then(books => {
          this.books = books[0].listOfItem;
          this.paginationParams.length = books[0].totalCount[0].count;
        });
      }
      if (user.books.length === 0) {
        this.books = [];
      }
    });
  }
}

<h3 *ngIf="!books.length">Your list is empty</h3>
<div
class="container"
*ngIf="books.length"
>
  <div class="input-field">
      <input type="text" id="text" [(ngModel)]='searchField' (ngModelChange)="this.onSearchFieldChange.next($event)">
      <label for="text">Seaarch field</label>
  </div>
  <p class="favoritesText">Favorites: </p>
  <ul class="book-card">
    <li
    class="row book-element"
    *ngFor="let book of books"
    >
      <img src={{book.image}} alt="book image" class="book-image col s3">
      <p class="col s6">
        <b>
          {{book.title}}
        </b>
      </p>
      <p class="description  col s7">
        <b>Categories:</b> <span *ngFor="let category of book.categories_list" class="chip">{{category.name}}</span><br>
        <b>Authors:</b> <span *ngFor="let author of book.authors_list" class="chip">{{author.name}}</span> 
      </p>
      <div class="col s2 center btn-section">
        <button class="btn green" (click)="openDialog(book)">
          Details
        </button>
        <button class="btn red" (click)="deleteDialog(book)">
          <i class="material-icons">
            delete
          </i>
        </button>
      </div>
    </li>
  </ul>
  <mat-paginator 
    [length] = "paginationParams.length"
    [pageSize] = "paginationParams.pageSize"
    [pageSizeOptions] = "[3, 5, 7, 10, 25, 50]"
    (page) = "paginationHandler($event)">
  </mat-paginator>
</div>
<app-modal></app-modal>

// client/client-react/src/component/Favorites/favorites.tsx
import React from 'react';
import UserService, { UserServiceClass } from '../../service/users.service';
import UserInfoService, { UserInfo } from '../../service/user-info.service';
import { debounceTime } from 'rxjs/operators';
import { Subject } from 'rxjs';
import { User } from '../../models/user.model';
import { PaginationEvent } from '../../models/pagination-event.model';
import { Book } from '../../models/book.model';
import { CategoryAuthor } from '../../models/category-author.model';
import './style.scss';
import ReactModal from 'react-modal';
import FavoritesDetailsModal from './favoritesDetailsModal/favoritesDetailsModal';
import FavoritesDeleteModal from './favoritesDeleteModal/favoritesDeleteModal';
import PaginationComponent from '../../shared/PaginationComponent/pagination';

const customStyles = {
  content : {
    top                   : '50%',
    left                  : '50%',
    right                 : 'auto',
    bottom                : 'auto',
    marginRight           : '-50%',
    transform             : 'translate(-50%, -50%)',
    minWidth              : '550px'
  }
};

interface State {
  user: User;
  pagination: PaginationEvent,
  books: Book[];
  favoritesDetailsId: string;
  favoritesDetails: boolean;
  favoritesDeleteId: string;
  favoritesDeleteModal: boolean;
}

export default class Favorites extends React.Component<any, State> {
  public userInfoService: UserInfo;
  public userService: UserServiceClass;
  public onSearchFieldChange: Subject<string>;

  constructor(props: any) {
    super(props);

    this.state = {
      user: {
        email: '',
        name: '',
        password: '',
        role: 2,
        _id: ''
      },
      pagination: {
        pageSize: 10,
        pageIndex: 0,
        length: 0
      },
      books: [],
      favoritesDetailsId: '',
      favoritesDetails: false,
      favoritesDeleteId: '',
      favoritesDeleteModal: false
    };

    this.onSearchFieldChange = new Subject<string>();
    this.onSearchFieldChange
    .pipe(debounceTime(500))
    .subscribe((value: string) => {
      this.searchFromFavorites(value)
    });

    this.userService = UserService;
    this.userInfoService = UserInfoService;

    this.searchFromFavorites = this.searchFromFavorites.bind(this);
    this.openBookDetails = this.openBookDetails.bind(this);
    this.favoritesDeleteModal = this.favoritesDeleteModal.bind(this);
    this.deleteBookFromFavorites = this.deleteBookFromFavorites.bind(this);
  }

  componentDidMount() {
    this.userService.getUser((this.userInfoService.getCurrentUser() as User).id as string)
    .then((user) => {
      if ((user.books as string[]).length > 0) {
        this.userService.getUserBooks(user.books as string[], this.state.pagination)
        .then(data => {
          this.setState({
            user,
            books: data[0].listOfItem as Book[],
            pagination: {
              ...this.state.pagination,
              length: data[0].totalCount[0].count
            }
          })
        })
      }
    });
    ReactModal.setAppElement('.favoritesComponent');
  }

  public searchFromFavorites(searchTitle: string): void {
    this.userService.getUser((this.userInfoService.getCurrentUser() as User).id as string)
    .then((user: User) => {
      if ((user.books as string[]).length > 0) {
        this.userService.getUserBooks(user.books as string[], this.state.pagination, searchTitle)
        .then(books => {
          if (books[0].listOfItem.length) {
            this.setState({            
              books: books[0].listOfItem as Book[],
              pagination: {
                ...this.state.pagination,
                length:  books[0].totalCount[0]
                ? books[0].totalCount[0].count
                : 0
              }
            });
          } else {
            alert('Book not found')
          }
        });
      }
    });
  }

  public deleteBookFromFavorites(bookId: string): void {
    const user = {...this.state.user} ; 
    user.books = (user.books as string[]).filter(book => {
      return bookId !== book;
    });
    this.userService.edit(this.state.user._id, user)
    .then(() => {
      this.setState({
        user,
        books: this.state.books.filter(book => {
          return book._id !== bookId;
        }),
        pagination: {
          ...this.state.pagination,
          length: this.state.pagination.length as number - 1
        }
      })
    })
  }
  
  public openBookDetails(bookId: string): void {
    if (bookId.length > 0) {
      this.setState({
        favoritesDetails: !this.state.favoritesDetails,
        favoritesDetailsId: bookId
      })
    } else {
      this.setState({
        favoritesDetails: !this.state.favoritesDetails
      })
    }
  }

  public favoritesDeleteModal(bookId: string): void {
    if (bookId.length > 0) {
      this.setState({
        favoritesDeleteModal: !this.state.favoritesDeleteModal,
        favoritesDeleteId: bookId
      })
    } else {
      this.setState({
        favoritesDeleteModal: !this.state.favoritesDeleteModal
      })
    }
  }

  render() {
    return (
      <div className="container favoritesComponent">
        <ReactModal
        isOpen={this.state.favoritesDetails as boolean}
        style={customStyles}
        contentLabel="Book's details">
          <FavoritesDetailsModal
            book={this.state.books.filter(book => {
              return book._id === this.state.favoritesDetailsId;
            })}
            close={this.openBookDetails}
          />
        </ReactModal>

        <ReactModal
        isOpen={this.state.favoritesDeleteModal as boolean}
        style={customStyles}
        contentLabel="Delete book modal">
          <FavoritesDeleteModal
            book={this.state.books.filter(book => {
              return book._id === this.state.favoritesDeleteId;
            })}
            delete={this.deleteBookFromFavorites}
            close={this.favoritesDeleteModal}/>
        </ReactModal>

        <div className="input-field">
            <input type="text" id="text" 
            onChange={event => this.onSearchFieldChange.next(event.target.value)}/>
            <label htmlFor="text">Seaarch field</label>
        </div>
        <p className="favoritesText">Favorites: </p>
        <ul className="book-card">
        { this.state.books.length > 0
          ? this.state.books.map((book) => {
            return (
            <li className="row book-element" key={book._id}>
              <img src={book.image as string} alt="book" className="book-image col s3" />
              <p className="col s6">
                <b>
                  {book.title}
                </b>
              </p>
              <p className="description  col s7">
                <b>Categories:</b>
                {(book.categories_list as CategoryAuthor[]).length > 0
                ? (book.categories_list as CategoryAuthor[]).map(category => {
                  return (
                    <span className="chip" key={category._id}>{category.name}</span>
                  )
                })
                : <span className='chip'>unknown</span>}
                <br />
                <b>Authors:</b>
                {(book.authors_list as CategoryAuthor[]).length > 0
                ? (book.authors_list as CategoryAuthor[]).map(author => {
                  return (
                    <span className="chip" key={author._id}>{author.name}</span>
                  )
                })
                : <span className='chip'>unknown</span>}
              </p>
              <div className="col s2 center btn-section">
                <button className="btn green"
                  onClick={() => this.openBookDetails(book._id as string)}
                >
                  Details
                </button>
                <button className="btn red"
                  onClick={() => {this.favoritesDeleteModal(book._id as string)}}>
                  <i className="material-icons">
                    delete
                  </i>
                </button>
              </div>
            </li>
            )
          })
          : <h3>Your list is empty</h3> }
        </ul>
        {this.state.pagination.length as number > 0
          ? <PaginationComponent
            pagination={this.state.pagination}
            onPageSizeChange={(pageSize: number) => {
              this.setState({
                pagination: {
                  ...this.state.pagination,
                  pageSize
                }
              }, this.componentDidMount)
            }}
            callback={(current, pageSize) => {
              this.setState({
                pagination: {
                  ...this.state.pagination,
                  pageIndex: current - 1,
                  pageSize
                }
              }, this.componentDidMount)
            }}
          />
          : null
        }
      </div>
    )
  }
}
