// client/client-react/src/shared/BookComponent/BookComponent.tsx
import React from "react";
import ReactModal from 'react-modal';
import { Book } from "../../models/book.model";
import { CategoryAuthor } from '../../models/category-author.model';
import './style.scss';
import { EditeModal } from "./editeModal/editeModal";
import DeleteModal from "./deleteModal/deleteModal";

const customStyles = {
  content : {
    top                   : '50%',
    left                  : '50%',
    right                 : 'auto',
    bottom                : 'auto',
    marginRight           : '-50%',
    transform             : 'translate(-50%, -50%)',
    minWidth              : '550px'
  }
};

interface BookProps {
  book: Book;
  buttonStatus: {
    editeBtn: boolean,
    deleteBtn: boolean,
    ddToDbBtn: boolean,
    addToFavoriteBtn: boolean
  };
  deleteFromDB: (book: Book) => void;
  addToFavorite: (book: Book) => void;
  editeBook: (book: Book) => void;
  addBookToDB: (book: Book) => void;
}

interface BookState {
  book: Book;
  addBookToFavorite: boolean;
  deleteFromFavorites: boolean;
  bookDeleteModal: boolean;
  bookEditeModal: boolean;
  options: any;
};

export class BookComponent extends React.Component<BookProps, BookState> {
  constructor(props: BookProps) {
    super(props as BookProps);

    this.state = {
      book: {
        ...this.props.book
      },
      addBookToFavorite: false,
      deleteFromFavorites: false,
      bookDeleteModal: false,
      bookEditeModal: false,

      options: [{name: 'Srigar', id: 1},{name: 'Sam', id: 2}],
    };

    this.addBookToFavoriteModal = this.addBookToFavoriteModal.bind(this);
    this.deleteFromFavorites = this.deleteFromFavorites.bind(this);
    this.bookDeleteModal = this.bookDeleteModal.bind(this);
    this.bookEditeModal = this.bookEditeModal.bind(this);
    this.deleteBookFromDB = this.deleteBookFromDB.bind(this);
    this.addBookToDB = this.addBookToDB.bind(this);
    this.addBooktoFavorite = this.addBooktoFavorite.bind(this);
  }

  componentDidMount() {
    ReactModal.setAppElement('.bookComponent')
  };
  
  public addBookToFavoriteModal(): void {
    this.setState({
      addBookToFavorite: !(this.state as any).addBookToFavorite
    })
  }

  public deleteFromFavorites(): void {
    this.setState({
      deleteFromFavorites: !(this.state as any).deleteFromFavorites
    })
  }

  public bookDeleteModal(): void {
    this.setState({
      bookDeleteModal: !(this.state as any).bookDeleteModal
    })
  }

  public bookEditeModal(): void {
    this.setState({
      bookEditeModal: !(this.state as any).bookEditeModal
    })
  }

  public deleteBookFromDB(): void {
    this.bookDeleteModal();
    this.props.deleteFromDB(this.props.book);
  }

  public addBookToDB(): void {
    this.props.addBookToDB(this.props.book)
  }

  public addBooktoFavorite(): void {
    this.props.addToFavorite(this.props.book);
  }

  render() {
    const image = this.props.book.image?
        this.props.book.image
        : this.props.book.imageLinks as {thumbnail: string}?
        (this.props.book.imageLinks as {thumbnail: string}).thumbnail
        : '';
    const categories = this.props.book.categories_list?
        (this.props.book.categories_list as CategoryAuthor[]).map((category: CategoryAuthor) => {
          return category.name;
        })
        : this.props.book.categories?
        this.props.book.categories
        : null;
    const authors = this.props.book.authors_list?
        (this.props.book.authors_list as CategoryAuthor[]).map((author: CategoryAuthor) => {
          return author.name;
        })
        : this.props.book.authors?
        this.props.book.authors
        : null;
    
    return (
      <div className="z-depth-4 bookComponent">
        <ReactModal
        isOpen={(this.state as any).bookDeleteModal as boolean}
        style={customStyles}
        contentLabel="Delete book from DataBase"
        >
          <DeleteModal 
            book={this.props.book}
            close={this.bookDeleteModal}
            deleteFromDB={this.deleteBookFromDB}
          />
        </ReactModal>

        <ReactModal
        isOpen={(this.state as any).bookEditeModal as boolean}
        style={customStyles}
        contentLabel="Edite book modal">
          <EditeModal 
            book={this.props.book}
            close={this.bookEditeModal}
            editeBook={this.props.editeBook}
          />
        </ReactModal>

        <div className="card horizontal">
          <div className="card-image">
            <img alt="Bookimage" src={image as string} className="book-image" />
            {
              this.props.buttonStatus.editeBtn ?
              <button
                onClick={this.bookEditeModal}
                className="btn edite-btn rework-btn"
                >
                <i className="material-icons">edite</i>
              </button>
              : null
            }
            {
              this.props.buttonStatus.deleteBtn ?
              <button
              onClick={this.bookDeleteModal}
              className="btn delete-btn rework-btn"
              >
                <i className="material-icons">delete</i>
              </button>
              : null
            }
          </div>
          <div className="card-stacked">
            <div className="card-content">
              <div className="card-title">
                <b>{this.props.book.title}</b>
              </div>
                <b>Categories: </b>
                { categories ?
                  (categories as string[]).map((category: string, index: number) => {
                  return (
                    <span
                    key={index}
                    className="chip"
                    >{category}</span>
                    )
                  })
                  : null }
              <br />
              <b>Author: </b>
              {authors ?
                (authors as string[]).map((author: string, index: number) => {
                return (
                    <span 
                    key={index}
                    className="chip"
                    >{author}</span>
                  )
                })
              : null }
              <p className="book-description"><span>
              <b>Description</b>:</span> {this.props.book.description}</p>
              <p><b>Pages: </b>{this.props.book.pageCount}</p>
            </div> 
            <div className="card-action">
              {this.props.buttonStatus.addToFavoriteBtn && !this.props.book.inFavorite ?
              <button
              className="btn green add-to-pro-btn"
              onClick={this.addBooktoFavorite}
              >
              add to 'My favorites'
              </button>
              : null}
              {this.props.buttonStatus.addToFavoriteBtn && this.props.book.inFavorite ?
              <button
              className="btn red add-to-pro-btn"
              onClick={this.addBooktoFavorite}
              >
              delete from 'My favorites'
              </button>
              : null}
              {this.props.buttonStatus.ddToDbBtn ?
              <button
                className="btn add-to-pro-btn"
                onClick={this.addBookToDB}
                disabled={this.props.book.alreadyExistInBD}
              >
              add to DB
              </button>
              : null}
            </div>
          </div>
        </div>
      </div>
    )
  }
}

// client/client-angular/src/app/shared/book/book.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Book } from 'src/app/models/book.model';
import { UserInfo } from 'src/app/service/user-info.service';
import { BookService } from 'src/app/service/books.service';
import { MatDialog } from '@angular/material/dialog';
import { BookEditeModalComponent } from './book-edite-modal/book-edite-modal.component';
import { BookDeleteModalComponent } from './book-delete-modal/book-delete-modal.component';
import { AddBookModalComponent } from './book-add-modal/add-book-modal.component';
import { UserService } from 'src/app/service/users.service';
import { BookDeleteFromFavModalComponent } from './book-delete-from-fav-modal/book-delete-from-fav-modal.component';

@Component({
  selector: 'app-book',
  templateUrl: './book.component.html',
  styleUrls: ['./book.component.scss']
})
export class BookComponent implements OnInit {
  @Input() book: Book;
  @Input() buttonStatus: {
    editeBtn: boolean,
    deleteBtn: boolean,
    addToDbBtn: boolean,
    addToFavoriteBtn: boolean
  };
  @Input() reloadPage: () => void;

  public bookImage: string | ArrayBuffer;
  public bookExistInFavorites: boolean;

  constructor(
    public userInfo: UserInfo,
    public bookService: BookService,
    public userService: UserService,
    public dialog: MatDialog
  ) {
    this.bookImage = '';
  }

  ngOnInit() {
    this.bookImage = this.book.imageLinks ? this.book.imageLinks.thumbnail : this.book.image;
  }

  public addBookToFavorite(book: Book): void {
    this.userService.addBookToProfile(book);
    this.confirmDialog();
  }

  public addBookToDB(book: Book): void {
    this.book.inFavorite = true;

    const newBook: Book = {
      title: book.title,
      authors: book.authors,
      categories: book.categories || [],
      description: book.description,
      image: book.imageLinks.thumbnail || '',
      pageCount: book.pageCount,
      printType: book.printType,
      industryIdentifiers: book.industryIdentifiers
    };
    this.bookService.addBookToDB(newBook);
  }

  public deleteBook(book: Book): void {
    this.bookService.deleteBook(book)
    .then(() => {
      this.reloadPage();
    });
  }

  public chooseEditeBook(book): void {
    this.dialog.open(BookEditeModalComponent, {
      data: {
        book,
        reloadPage: this.reloadPage
      }
    });
  }

  public deleteDialog(book: Book): void {
    this.dialog.open(BookDeleteModalComponent, {
      data: {
        book,
        deleteBook: this.deleteBook.bind(this),
        reloadPage: this.reloadPage
      }
    });
  }

  public confirmDialog(): void {
    this.dialog.open(AddBookModalComponent, {
      data: {
        book: this.book,
        reloadPage: this.reloadPage
      }
    });
  }

  public deleteFromFavorites(): void {
    this.dialog.open(BookDeleteFromFavModalComponent, {
      data: {
        book: this.book,
        reloadPage: this.reloadPage
      }
    });
  }
}

<div class="z-depth-4">
  <div class="card horizontal">
    <div class="card-image">
      <img alt="Book image" src="{{bookImage}}" class="book-image">
      <button
        (click)="chooseEditeBook(book)"
        class="btn edite-btn rework-btn"
        *ngIf="buttonStatus.editeBtn">
        <i class="material-icons">edite</i>
      </button>
      <button 
        (click)="deleteDialog(book)"
        class="btn delete-btn rework-btn"
        *ngIf="buttonStatus.editeBtn">
        <i class="material-icons">delete</i>
      </button>
    </div>
    <div class="card-stacked">
      <div class="card-content">
        <div class="card-title">
          <b>{{book.title}}</b>
        </div>     
        <b *ngIf="book.categories_list || book.categories">Categories: </b>
          <span class="chip" *ngFor="let category of book.categories_list || book.categories">
            {{category.name || category}}<br>
          </span>
        <br>
        <b *ngIf="book.authors_list || book.authors">Authors: </b>
        <span class="chip" *ngFor="let author of book.authors_list || book.authors">
          {{author.name || author}}
        </span>
        <p class="book-description"><span *ngIf="book.description"><b>Description</b>:</span> {{book.description}}</p>
        <p><b>Pages: </b>{{book.pageCount}}</p>
      </div> 
      <div class="card-action">
        
        <button
          *ngIf="buttonStatus.addToFavoriteBtn  && !book.inFavorite"
          class="btn green add-to-pro-btn"
          (click)="addBookToFavorite(book)"
        >
        add to 'My favorites'
        </button>
        <button
          *ngIf="buttonStatus.addToFavoriteBtn && book.inFavorite"
          class="btn red add-to-pro-btn"
          (click)="deleteFromFavorites(book)"
        >
        delete from 'My favorites'
        </button>

        <button
          *ngIf="buttonStatus.addToDbBtn"
          class="btn add-to-pro-btn"
          [disabled]="book.alreadyExistInBD"
          (click)="addBookToDB(book)"
        >
        add to DB
        </button>
      </div>
    </div>
  </div>
</div>
