// client/client-angular/src/app/admin/google-book/google-book.component.ts
import { Component, OnInit } from '@angular/core';
import { GoogleBooks } from '../../service/google-books.service';
import { BookService } from '../../service/books.service';
import { Subject } from 'rxjs';
import { debounceTime } from 'rxjs/operators';
import { PaginationEvent } from 'src/app/models/pagination-event';
import { Book } from 'src/app/models/book.model';

@Component({
  selector: 'app-google-book',
  templateUrl: './google-book.component.html',
  styleUrls: ['./google-book.component.scss']
})
export class GoogleBookComponent implements OnInit {

  public searchString: string;
  public searchStringUpdate: Subject<string>;
  public listOfBook: Book[];
  public paginationParams: PaginationEvent;

  constructor(
    private googleBooks: GoogleBooks
    ) {
      this.searchStringUpdate = new Subject<string>();
      this.searchString = this.googleBooks.getPageInfo().searchResult;
      this.listOfBook = this.googleBooks.getPageInfo().currentItems;
      this.paginationParams = this.googleBooks.getPageInfo().paginationParams;

      this.searchStringUpdate.pipe(
        debounceTime(500)
      ).subscribe(value => {
        if (this.searchString.length > 0) {
          this.searchForBook(value);
        }
      });
    }

  ngOnInit() {}

  public searchForBook(searchString: string): void {
    this.googleBooks.searchForBook(searchString)
    .then((result: any) => { // make
      this.listOfBook = result;
    });
  }

  public paginationHandler(eventPage: PaginationEvent): PaginationEvent {
    this.googleBooks.getPageInfo().paginationParams = eventPage;

    if (this.searchString.length > 0) {
      this.searchForBook( this.searchString);
    }
    return eventPage;
  }
}

<div class="container">
    <div class="input-field">
        <input id="search" type="text" class="validate" [(ngModel)]="this.searchString" (ngModelChange)="this.searchStringUpdate.next($event)">
        <label for="search" [ngClass]="{active: this.searchString}">Search field</label>
    </div>
    <app-book 
    *ngFor="let book of listOfBook"
    [book]="book"
    [buttonStatus]="{
        editeBtn: false,
        deleteBtn: false,
        addToFavoriteBtn: false,
        addToDbBtn: true
    }"
    ></app-book>
    <mat-paginator 
    [length] = "paginationParams.length"
    [pageSize] = "paginationParams.pageSize"
    [pageSizeOptions] = "[3, 5, 7, 10]"
    (page) = "paginationHandler($event)">
    </mat-paginator>
</div>

// client/client-react/src/Admin/Google-Book/index.tsx
import React, { Props, ChangeEvent } from 'react';
import GoogleBooks from '../../service/google-books.service';
import { BookService } from '../../service/books.service';
import { Book } from '../../models/book.model';
import { BookComponent } from '../../shared/BookComponent';
import { Pagination } from './../../shared/Pagination';
// const Filter = React.lazy(() => import('../../shared/filter'))

export class GoogleBook extends React.Component {
  constructor(
    props: Props<any>
    ) {
    super(props);
    this.googleBooks = new GoogleBooks(new BookService());
    this.state = {
      searchString:  '',
      listOfBook: [],
      paginationParams: []
    };
    this.handleChange = this.handleChange.bind(this);
    this.handleClick = this.handleClick.bind(this);
    this.paginationHandler = this.paginationHandler.bind(this)
  }
  public googleBooks: GoogleBooks;


  public handleChange(event: ChangeEvent<HTMLInputElement>): void {
    this.setState({
      ...this.state,
      searchString: event.target.value
    })
  }
  
  public handleClick(event: React.MouseEvent<HTMLButtonElement>): void {
    this.googleBooks.searchForBook((this.state as any).searchString)
    .then(() => {
      this.setState({
        ...this.state,
        listOfBook: this.googleBooks.getPageInfo().currentItems
      })
      console.log(this.state);
    })
  }

  public paginationHandler(event: any) {
    console.log(event.target);
    
  }

  render() {
    return (
      <div className="container">
        <div>
          <label> Search field
            <input id="search" type="text" className="validate"
            onChange={this.handleChange}
            />
          </label>
          <button className="btn"
          onClick={this.handleClick}
          >Search</button>
        </div>
        {(this.state as any).listOfBook.map((book: Book, index: number) => {
          return (
            <BookComponent
              key={index}
              book={book}
              buttonStatus={{
                editeBtn: false,
                deleteBtn: false,
                ddToDbBtn: false,
                addToFavoriteBtn: true
              }}
            />
            )
          })}
        <div onClick={(event) => this.paginationHandler(event)}>
        
        <Pagination
          pageIndex={0}
          pageSize={5}
          length={5}
          // [length] = "paginationParams.length"
          // [pageSize] = "paginationParams.pageSize"
          // [pageSizeOptions] = "[3, 5, 7, 10]"
          // (page) = "paginationHandler($event)">
        />
        </div>
      </div>
    )
  }
}
