// client/client-react/src/shared/FilterComponent/FilterComponent.tsx
import React from 'react'
import { connect } from 'react-redux';
import queryString from 'query-string';
import { CategoryAuthor } from '../../models/category-author.model';
import { BookService } from '../../service/books.service';
import { FilterState } from '../../store/reducers/filterReducer';
import * as filterAction from '../../store/actions/filterAction';
import './style.scss';
import { Subject } from 'rxjs';
import { debounceTime } from 'rxjs/operators';

interface Props{
  history: any;
  authors : any;
  categories:any;
  search: string;
  setFilter:( data: any)=> void;
  getSomeBooks: () => void;
  refreshFilter: () => void;
}

interface State {
  data: {
    title: string | undefined,
    categories: CategoryAuthor[],
    authors: CategoryAuthor[]
  }
}

class Filter extends React.Component<Props, State> {
  private bookService: BookService;
  public onSearchStringChange: Subject<string>;
  
  constructor(props: Props) {
    super(props);

    this.state = {
      data: {
        title: undefined,
        categories: [],
        authors: []
      }
    }

    this.onSearchStringChange = new Subject();
    this.onSearchStringChange.pipe(debounceTime(500))
    .subscribe(value => {
      this.setState({
        data: {
          ...this.state.data,
          title: value
        }
      }, () => this.filterHandler(null))
    })

    this.bookService = new BookService();
    this.filterHandler = this.filterHandler.bind(this);
    this.refreshFilter = this.refreshFilter.bind(this);
    this.setFilterInitialState = this.setFilterInitialState.bind(this);
  }

  UNSAFE_componentWillMount() {
    this.setFilterInitialState();
  }

  public setFilterInitialState() {
    if ((this.props as any).location.search) {
      console.log((this.props as any).location.search);
      
      const query = queryString.parse((this.props as any).location.search);
      if (query.categories) {
        this.props.categories.forEach((category: CategoryAuthor) => {
          category.checked = (query.categories as string[]).indexOf(category._id) !== -1  ? true: false
        })
      }
      if (query.authors) {
        this.props.authors.forEach((author: CategoryAuthor) => {
          author.checked = (query.categories as string[]).indexOf(author._id) !== -1  ? true: false
        })
      }
      if (query.title) {
        this.setState({
          data: {
            ...this.state.data,
            title: query.title as string
          }
        })
      }
    } else {
      this.props.categories.forEach((category: CategoryAuthor) => {
        category.checked = false;
      });
      this.props.authors.forEach((author: CategoryAuthor) => {
        author.checked = false;
      });
    }
  }

  public filterHandler(obj: CategoryAuthor | null, value?: string) {
    let data: {
      title?: string,
      categories?: CategoryAuthor[],
      authors?: CategoryAuthor[]
    } = {};

    if (obj && obj !== undefined) {
      (obj as CategoryAuthor).checked = !(obj as CategoryAuthor).checked;
    }

    data.title = this.state.data.title

    data.categories = this.props.categories.filter((obj: any) => {
      return obj.checked;
    }).map((obj: any) => {
      return obj._id;
    });

    data.authors = this.props.authors.filter((obj: any) => {
      return obj.checked;
    }).map((obj: any) => {
      return obj._id;
    });

    (this.props as any).push({
      pathname: '/filtered',
      search: queryString.stringify(data)
    });

    this.props.getSomeBooks();
  }

  public refreshFilter() {
    console.log('this.props.', this.props);

    (this.props as any).push({
      pathname: '/filtered',
      search: ''
    });
    // this.componentDidMount()
    // this.bookService.getAllAuthors()
    // .then((authors: CategoryAuthor[]) => {
    //   authors = authors.map(author => {
    //     return {
    //       ...author,
    //       checked: false
    //     }
    //   })
    //   this.bookService.getAllCategories()
    //   .then((categories: CategoryAuthor[]) => {
    //     categories = categories.map((category: CategoryAuthor) => {
    //       return {
    //         ...category,
    //         checked: false
    //       }
    //     });
    //     this.props.setFilter({
    //       authors,
    //       categories,
    //       title: ''
    //     });
    //   });
    // });
  }

  render() {
    return (
      <div className="col s2 filters">
        <div className="input-field">
          <input type="text" id="searchField" 
          onChange={event => this.onSearchStringChange.next(event.target.value)}
          defaultValue={this.state.data.title}/>
          <label
          className={this.state.data.title ? 'active' : ''}
          >Search Field</label>
        </div>
        {
          this.props.categories.map((category: CategoryAuthor, index: number) => {
            return (
              <label key={index}>
                <input type="checkbox"
                defaultChecked={category.checked}
                onClick={() => this.filterHandler(category)}/>
                <span>{category.name}</span>
              </label>
            )
          })
        }
        <hr/>
        {
          this.props.authors.map((author: CategoryAuthor, index: number) => {
            return (
              <label key={index}>
                <input type="checkbox"
                defaultChecked={author.checked}
                onClick={() => this.filterHandler(author)}/>
                <span>{author.name}</span>
              </label>
            )
          })
        }
        <hr/>
        <br/>
        {/* <button
          className="btn green darken-2"
          onClick={this.refreshFilter}
        >refresh filter</button> */}
      </div>
    )
  }
}

const mapStateToProps = (state: any) => {
  return {
    ...state.filterReducer
  }
};

const mapDispatchToProps = (dispatch: any) => {
  return {
    setTitle: (title: string) => dispatch(filterAction.setTitle(title)),
    setCategories: (categories: CategoryAuthor[]) => dispatch(filterAction.setCategories(categories)),
    setAuthor: (authors: CategoryAuthor[]) => dispatch(filterAction.setAuthor(authors)),
    setFilter: (data: FilterState) => dispatch(filterAction.setFilter(data)),
    refreshFilter: () => dispatch(filterAction.refreshFilterData())
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(Filter)

// client/client-angular/src/app/shared/filter/filter.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { BookService } from 'src/app/service/books.service';
import { CategoryAuthor } from 'src/app/models/category-author.model';
import { ActivatedRoute } from '@angular/router';
import { Subject } from 'rxjs';
import { debounceTime } from 'rxjs/operators';

@Component({
  selector: 'app-filter',
  templateUrl: './filter.component.html',
  styleUrls: ['./filter.component.scss']
})
export class FilterComponent implements OnInit {
  @Input() getFilteredBooks: (data) => void;
  @Input() getAllBooks: () => void;

  public authors: CategoryAuthor[];
  public categories: CategoryAuthor[];
  public filterData = {
    title: '',
    categories: new Set(),
    authors: new Set()
  };
  public searchField = '';
  public searchStringUpdate = new Subject<string>();
  public linkParams;

  constructor(
    private bookService: BookService,
    private activeRoute: ActivatedRoute,
  ) {
    this.bookService = new BookService();
    this.searchStringUpdate
      .pipe(debounceTime(500))
      .subscribe(value => {
        console.log(value);
        this.filtering();
      });
  }

  ngOnInit() {
    this.linkParams = this.activeRoute.snapshot.queryParams;
    this.searchField = this.linkParams.title;
    this.getAuthors();
    this.getCategories();
  }

  public getAuthors(): void {
    this.bookService.getAllAuthors()
      .then((authors: CategoryAuthor[]) => {
        this.authors = authors.map(author => {
          return {
            ...author,
            checked: this.linkParams.hasOwnProperty('authors') ?
              this.linkParams.authors.indexOf(author._id) === -1 ? false : true
              : false
          };
        });
      });
  }

  public getCategories(): void {
    this.bookService.getAllCategories()
      .then((categories: CategoryAuthor[]) => {
        this.categories = categories.map(category => {
          return {
            ...category,
            checked: this.linkParams.hasOwnProperty('categories') ?
              this.linkParams.categories.indexOf(category._id) === -1 ? false : true
              : false
          };
        });
      });
  }

  public filtering(catauth?: CategoryAuthor): void {
    if (catauth !== undefined) {
      catauth.checked = !catauth.checked;
    }
    const data = {
      title: this.searchField,
      categories: [],
      authors: []
    };

    data.categories = this.categories.filter((obj) => {
      return obj.checked;
    }).map(obj => {
      return obj._id;
    });

    data.authors = this.authors.filter((obj) => {
      return obj.checked;
    }).map(obj => {
      return obj._id;
    });

    this.getFilteredBooks(data);
  }
}

<div class="col s2 filters">
  <div class="input-field">
    <input type="text" id="searchField"
      [(ngModel)]="this.searchField"
      (ngModelChange)="this.searchStringUpdate.next($event)"
    >
    <label for="searchField"
    [ngClass]="{active: this.searchField}"      
    >Search Field</label>
  </div>
  <div class="category-input" *ngFor="let category of categories">
    <input type="checkbox" id={{category._id}} [checked]="category.checked" (change)="filtering(category)"/>
    <label for={{category._id}}>{{category.name}}</label>
  </div>
  <hr>
  <div class="author-input" *ngFor="let author of authors">
    <input type="checkbox" id={{author._id}} [(checked)]="author.checked" (change)="filtering(author)"/>
    <label for={{author._id}}>{{author.name}}</label>
  </div>
  <hr>
</div>
