// client/client-react/src/Admin/Google-Book/googleBook.tsx
import React, { Props } from 'react';
import GoogleBooks from '../../service/google-books.service';
import { BookService } from '../../service/books.service';
import { Book } from '../../models/book.model';
import { BookComponent } from '../../shared/BookComponent/BookComponent';
import { Pagination } from '../../shared/Pagination/pagination';
// const Filter = React.lazy(() => import('../../shared/filter'))
import { debounceTime } from 'rxjs/operators';
import { Subject } from 'rxjs';


export class GoogleBook extends React.Component {
  public googleBooks: GoogleBooks;
  private bookService: BookService;
  public onSearchFieldChange: Subject<string>;

  constructor(
    props: Props<any>
    ) {
    super(props);
    this.googleBooks = new GoogleBooks(new BookService());
    this.bookService = new BookService();
    this.state = {
      listOfBook: [],
      paginationParams: []
    };
  
    this.onSearchFieldChange = new Subject<string>();
    this.onSearchFieldChange
    .pipe(debounceTime(500))
    .subscribe((value: string) => {
      if (value.length > 0) {
        this.googleBooks.searchForBook(value)
        .then(() => {
          this.setState({
            ...this.state,
            listOfBook: this.googleBooks.getPageInfo().currentItems
          })
        })
      }
    });

    this.paginationHandler = this.paginationHandler.bind(this);
    this.deleteBookFromDB = this.deleteBookFromDB.bind(this);
  }

  shouldComponentUpdate() {
    return true;
  }

  public paginationHandler(event: any) {
    console.log(event.target);
  }

  public deleteBookFromDB(data: Book) {
    this.bookService.deleteBook(data)
    .then((response) => {
      console.log(response)
    })
  }

  render() {
    return (
      <div className="container">
        <div>
          <label> Search field
            <input id="search" type="text" className="validate"
            onChange={event => this.onSearchFieldChange.next(event.target.value)}
            />
          </label>
        </div>
        {(this.state as any).listOfBook.map((book: Book, index: number) => {
          return (
            <BookComponent
              key={index}
              book={book}
              buttonStatus={{
                editeBtn: false,
                deleteBtn: false,
                ddToDbBtn: false,
                addToFavoriteBtn: true
              }}
              deleteFromDB={this.deleteBookFromDB}
              addToFavorite={() => {}}
              editeBook={() => {}}
            />
            )
          })}
        
        <Pagination
          pageIndex={0}
          pageSize={5}
          length={5}
          // [length] = "paginationParams.length"
          // [pageSize] = "paginationParams.pageSize"
          // [pageSizeOptions] = "[3, 5, 7, 10]"
          // (page) = "paginationHandler($event)">
        />
      
      </div>
    )
  }
}

// client/client-angular/src/app/components/google-book/google-book.component.ts
import { Component, OnInit } from '@angular/core';
import { GoogleBooks } from '../../services/google-books.service';
import { BookService } from '../../services/books.service';
import { Subject } from 'rxjs';
import { debounceTime } from 'rxjs/operators';
import { PaginationEvent } from 'src/app/models/pagination-event.model';
import { Book } from 'src/app/models/book.model';
import { UserInfo } from 'src/app/services/user-info.service';

@Component({
  selector: 'app-google-book',
  templateUrl: './google-book.component.html',
  styleUrls: ['./google-book.component.scss']
})
export class GoogleBookComponent implements OnInit {

  public searchString: string;
  public searchStringUpdate: Subject<string>;
  public listOfBook: Book[];
  public paginationParams: PaginationEvent;

  constructor(
    private googleBooks: GoogleBooks,
    public userInfo: UserInfo
    ) {
      this.searchStringUpdate = new Subject<string>();
      this.searchString = this.googleBooks.getPageInfo().searchResult;
      this.listOfBook = this.googleBooks.getPageInfo().currentItems;
      this.paginationParams = this.googleBooks.getPageInfo().paginationParams;

      this.searchStringUpdate.pipe(
        debounceTime(500)
      ).subscribe(value => {
        if (this.searchString.length > 0) {
          this.searchForBook(value);
        }
      });
    }

  ngOnInit() {}

  public searchForBook(searchString: string): void {
    this.googleBooks.searchForBook(searchString)
    .then((result: any) => { // make
      this.listOfBook = result;
    });
  }

  public paginationHandler(eventPage: PaginationEvent): PaginationEvent {
    this.googleBooks.getPageInfo().paginationParams = eventPage;

    if (this.searchString.length > 0) {
      this.searchForBook( this.searchString);
    }
    return eventPage;
  }
}
