// client/client-react/src/Shared/Catalog/Catalog.tsx
import React from 'react';
import Axios from 'axios';
import { NavLink } from 'react-router-dom';
import { Book } from '../../models/book.model';
import { User } from '../../models/user.model';
import GoogleBook from '../../components/GoogleBook/GoogleBook';
import { BookService } from '../../service/books.service';

import './Catalog.scss'

type CatalogProps = {
  searchString: string,
  currentItems: Book[],
  availablePages: number[],
  currentPage: number,
  params: {
    startIndex: number,
    maxResult: number
  }
}

class Catalog extends React.Component<{}, CatalogProps> {
  constructor(props: CatalogProps) {
    super(props);

    this.state = {
      searchString: '',
      currentItems: [],
      availablePages: [],
      currentPage: 0,
      params: {
        startIndex: 0,
        maxResult: 10
      }
    };
    this.inputHandler = this.inputHandler.bind(this);
    this.buttonHandler = this.buttonHandler.bind(this);
  };

  inputHandler(event: React.ChangeEvent<HTMLInputElement>) {
    this.setState({
      searchString: event.target.value
    });
  };

  buttonHandler(params: {startIndex: number, maxResult: number}) {
    const url = `https://www.googleapis.com/books/v1/volumes?q=${this.state.searchString}`;
    const currentItems: Book[] = [];
    let availablePages: number[] = [];  
    let currentPage;

    Axios.get(url, {params})
    .then(res => {
      res.data.items.forEach((element: {volumeInfo: Book}) => {
        currentItems.push(element.volumeInfo);
      });

      if (0 === params.startIndex) {
        const countPage = Math.ceil(res.data.totalItems / 20);

        for (let i = 0; i < countPage; i++) {
          availablePages.push(i);
        }

        this.setState({
          availablePages
        })

        currentPage = 0;
      }

      currentPage = params.startIndex / 10;

      this.setState({
        currentItems,
        currentPage
      });
      return res;
    })
    .catch(err => console.log(err));
  }

  changePage(page: number) {
    this.setState({ currentPage: page });

    this.buttonHandler({
      startIndex: page*10,
      maxResult: 10
    });
  }

  addBookToDB(cbook: Book, user: User) { // user in ardument
    console.log('book: ', cbook, 'user: ', user)
    const book = {
      title: cbook.title.toLowerCase(),
      authors: cbook.authors.map((element: string) => element.toLowerCase()),
      categories: cbook.categories ? cbook.categories.map((element: string) => element.toLowerCase()) : [],
      description: cbook.description,
      image: cbook.imageLinks ? cbook.imageLinks.thumbnail : '',
      pageCount: cbook.pageCount,
      printType: cbook.printType.toLowerCase(),
      industryIdentifiers: cbook.industryIdentifiers
    };
    console.log('books in catalog', book);
    BookService.addBookToDB(book, user)
  } 

  render() {
    return (
      <div className="container">
        <div className="input-field">
          <input 
            id="search" 
            type="text" 
            className="validate"
            onChange={this.inputHandler}
          />
          <label htmlFor="search" className={this.state.searchString.length > 0 ? 'active' : ''}>Search field</label>
        </div>
        <button 
          className="btn"
          onClick={()=> {this.buttonHandler(this.state.params)}}
        >GO
        </button>

        { this.state.currentItems.map((item, index) => {
          return (
            <GoogleBook 
              book={item}
              key={index}
              inProfile={false}
              btnDelete={false}
              btnEdite={false}
              addBook={this.addBookToDB} 
            />
          )
        }) }
        
        <ul className="pagination">
          { this.state.availablePages ?
            this.state.availablePages.map((page, index) => {
              return (
                <li
                  className={(this.state.currentPage === page) ? "waves-effect active" : "waves-effect"}
                  key={index}
                  onClick={() => {this.changePage(page)}}
                  >
                  <NavLink to="/catalog">{page + 1}</NavLink>
                </li>
              )
            })
            : null
          }        
        </ul>
      </div>
    )
  }
}

export default Catalog;

// client/client-angular/src/app/shared/catalog/catalog.component.ts
import { Component, OnInit } from '@angular/core';
import { GoogleBooks } from '../../service/google-books.service';
import { BookService } from '../../service/books.service';
import { UserInfo } from '../../service/user-info.service';
import { Book } from 'src/app/models/book.model';
import { User } from 'src/app/models/user.model';

@Component({
  selector: 'app-catalog',
  templateUrl: './catalog.component.html',
  styleUrls: ['./catalog.component.scss']
})
export class CatalogComponent implements OnInit {

  public searchString: string;
  public listOfBook: any = this.googleBooks.getPageInfo().currentItems;
  public currentPage: number = this.googleBooks.getPageInfo().currentPage;

  constructor(
    private googleBooks: GoogleBooks,
    private booksService: BookService,
    private userInfo: UserInfo // use in template
    ) { }

  ngOnInit() {
  }

  public searchForBook(searchString: string, configForBookReq: {startIndex: number, maxResults: number}) {
    this.googleBooks.searchForBook(searchString, configForBookReq);
    this.currentPage  = configForBookReq.startIndex;
  }

  public changePage(page: number) {
    this.searchForBook( this.searchString, {startIndex: page * 10, maxResults: 10});
    this.currentPage = page;
  }

  public addBookToDB(book: Book, user: User) {
    const newBook: Book = {
      title: book.title.toLowerCase(),
      authors: book.authors.map(element => element.toLowerCase()),
      categories: book.categories ? book.categories.map(element => element.toLowerCase()) : [],
      description: book.description,
      image: book.imageLinks.thumbnail || '',
      pageCount: book.pageCount,
      printType: book.printType.toLowerCase(),
      industryIdentifiers: [...book.industryIdentifiers]
    };
    this.booksService.addBookToDB(newBook, user);
  }
}

<div class="container">
    <div class="input-field">
        <input id="search" type="text" class="validate" [(ngModel)]="this.searchString">
        <label for="search" [ngClass]="{active: this.searchString}">Search field</label>
    </div>
    <button class="btn" (click)="searchForBook( this.searchString, {startIndex: 0, maxResults: 10})">GO</button>
    <div class="catalog-list col s12 m7 z-depth-4" *ngFor="let book of listOfBook">
        <div class="card horizontal">
            <div class="card-image">
                <img src="{{book.imageLinks ? book.imageLinks.thumbnail : '../../assets/default-image-book.png'}}">
            </div>
            <div class="card-stacked">
                <div class="card-content">
                    <div class="card-title"><p><b>{{book.title}}</b></p></div>
                    <b *ngIf="book.categories">Categories: </b>
                    <div class="chip" *ngFor="let categorie of book.categories">
                        {{categorie}}
                    </div>
                    <br>
                    <b *ngIf="book.authors">Authors: </b>
                    <div class="chip" *ngFor="let author of book.authors">
                        {{author}}
                    </div>
                    <p><span *ngIf="book.description"><b>Description</b>:</span> {{book.description}}</p>
                </div> 
                <div class="card-action">
                    <button
                        class="btn add-to-pro-btn"
                        (click)="addBookToDB(book, this.userInfo.getCurrentUser())"
                    >
                    add to 'my list'
                    </button>
                    <button
                        class="btn"
                        (click)="addBookToDB(book)"
                    >
                    add to database
                    </button>
                </div>
            </div>
        </div>
    </div>
    <ul class="pagination">
        <li class="waves-effect"
            *ngFor="let page of this.googleBooks.getPageInfo().availablePages"
            [ngClass]="{active: (this.currentPage === page)}"
            (click)="this.changePage(page)"
            >
            <a routeLink="catalog">{{page + 1}}</a>
        </li>
    </ul>
</div>
