// client/client-react/src/shared/Favorites/favorites.tsx
import React from 'react';
import { UserService } from '../../service/users.service';
import { UserInfoService } from '../../service/user-info.service';
import { debounceTime } from 'rxjs/operators';
import { Subject } from 'rxjs';
import { User } from '../../models/user.model';
import { PaginationEvent } from '../../models/pagination-event.model';

interface State {
  pagination: PaginationEvent
}

export default class Favorites extends React.Component<any, State> {
  public userInfoService: UserInfoService;
  public userService: UserService;
  public onSearchFieldChange: Subject<string>;

  constructor(props: any) {
    super(props);

    this.state = {
      pagination: {
        pageSize: 10,
        pageIndex: 0,
        length: 0
      }
    };

    this.onSearchFieldChange = new Subject<string>();
    this.onSearchFieldChange
    .pipe(debounceTime(500))
    .subscribe((value: string) => {
      console.log(value);
      
    });

    this.userService = new UserService();
    this.userInfoService = new UserInfoService();
  }

  componentDidMount() {
    this.userService.getUser((this.userInfoService.getCurrentUser() as User).id as string)
    .then((user) => {
      
      if ((user.books as string[]).length > 0) {
        this.userService.getUserBooks(user.books as string[], this.state.pagination)
        .then(data => {
          
        })
      }
    })
  }

  render() {
    return (
        <div className="container">
          <h3>Your list is empty</h3>
          <div className="input-field">
              <input type="text" id="text" 
              onChange={event => this.onSearchFieldChange.next(event.target.value)}
              />
              <label htmlFor="text">Seaarch field</label>
          </div>
          <p className="favoritesText">Favorites: </p>
          <ul className="book-card">
            <li
            className="row book-element"
            >
              {/* <img src={book.image} alt="book image" className="book-image col s3" /> */}
              <p className="col s6">
                <b>
                  {/* {book.title} */}
                </b>
              </p>
              <p className="description  col s7">
                {/* <b>Categories:</b> <span className="chip">{category.name}</span> */}
                <br />
                {/* <b>Authors:</b> <span  className="chip">{author.name}</span>  */}
              </p>
              <div className="col s2 center btn-section">
                <button className="btn green">
                  Details
                </button>
                <button className="btn red">
                  <i className="material-icons">
                    delete
                  </i>
                </button>
              </div>
            </li>
          </ul>
        </div>
    )
  }
}

// client/client-angular/src/app/components/favorites/favorites.component.ts
import { Component, OnInit } from '@angular/core';
import { UserInfo } from 'src/app/services/user-info.service';
import { UserService } from 'src/app/services/users.service';
import { Book } from 'src/app/models/book.model';
import {MatDialog} from '@angular/material/dialog';
import { FavoritesModalComponent } from './favorites-modal/favorites-modal.component';
import { User } from 'src/app/models/user.model';
import { FavoritesDeleteModalComponent } from './favorite-delete-modal/favorites-delete-modal.component';
import { Subject } from 'rxjs';
import { debounceTime } from 'rxjs/operators';
import { PaginationEvent } from 'src/app/models/pagination-event.model';

@Component({
  selector: 'app-favorites',
  templateUrl: './favorites.component.html',
  styleUrls: ['./favorites.component.scss']
})
export class FavoritesComponent implements OnInit {
  public books: Book[] = [];
  public user: User;
  public pageOfItems: Book[];
  public searchField: string;
  public onSearchFieldChange: Subject<string>;
  public paginationParams: PaginationEvent = {
    pageIndex: 0,
    pageSize: 5,
    previousPageIndex: 0,
    length: 0
  };

  constructor(
    private userInfo: UserInfo,
    private userService: UserService,
    public dialog: MatDialog
  ) {
    this.onSearchFieldChange = new Subject<string>();
    this.onSearchFieldChange
      .pipe(debounceTime(500))
      .subscribe(value => {
        this.searchFromFavorites();
      });
  }

  ngOnInit() {
    this.userService.getUser(this.userInfo.getCurrentUser().id)
    .then((user: User) => {
      this.user = user;
      if (user.books.length > 0) {
        this.userService.getUserBooks(user.books as string[], this.paginationParams)
        .then(data => { // make response type
          this.books = data[0].listOfItem;
          this.paginationParams.length = data[0].totalCount[0].count;
        });
      }
      if (user.books.length === 0) {
        this.books = [];
      }
    });
  }

  public paginationHandler(pageEvent: PaginationEvent): PaginationEvent {
    this.paginationParams = pageEvent;
    if (this.searchField && this.searchField.length) {
      this.searchFromFavorites();
      return pageEvent;
    }
    this.ngOnInit();
    return pageEvent;
  }

  public openDialog(book: Book): void {
    this.dialog.open(FavoritesModalComponent, {
      data: {
        book
      }
    });
  }

  public deleteDialog(book: Book): void {
   this.dialog.open(FavoritesDeleteModalComponent, {
      data: {
        book,
        allBooks: this.books,
        user: this.user,
        delete: this.deleteBookFromFavorite.bind(this)
      }
    });
  }

  public deleteBookFromFavorite(user: User): void {
    this.userService.edit(this.user._id, user)
    .then(() => {
      this.ngOnInit();
    });
  }

  public searchFromFavorites(): void {
    this.userService.getUser(this.userInfo.getCurrentUser().id)
    .then((user: User) => {
      this.user = user;
      if (user.books.length > 0) {
        this.userService.getUserBooks(user.books as string[], this.paginationParams, this.searchField)
        .then(books => {
          this.books = books[0].listOfItem;
          this.paginationParams.length = books[0].totalCount[0].count;
        });
      }
      if (user.books.length === 0) {
        this.books = [];
      }
    });
  }
}

<h3 *ngIf="!books.length">Your list is empty</h3>
<div
class="container"
*ngIf="books.length"
>
  <div class="input-field">
      <input type="text" id="text" [(ngModel)]='searchField' (ngModelChange)="this.onSearchFieldChange.next($event)">
      <label for="text">Seaarch field</label>
  </div>
  <p class="favoritesText">Favorites: </p>
  <ul class="book-card">
    <li
    class="row book-element"
    *ngFor="let book of books"
    >
      <img src={{book.image}} alt="book image" class="book-image col s3">
      <p class="col s6">
        <b>
          {{book.title}}
        </b>
      </p>
      <p class="description  col s7">
        <b>Categories:</b> <span *ngFor="let category of book.categories_list" class="chip">{{category.name}}</span><br>
        <b>Authors:</b> <span *ngFor="let author of book.authors_list" class="chip">{{author.name}}</span> 
      </p>
      <div class="col s2 center btn-section">
        <button class="btn green" (click)="openDialog(book)">
          Details
        </button>
        <button class="btn red" (click)="deleteDialog(book)">
          <i class="material-icons">
            delete
          </i>
        </button>
      </div>
    </li>
  </ul>
  <mat-paginator 
    [length] = "paginationParams.length"
    [pageSize] = "paginationParams.pageSize"
    [pageSizeOptions] = "[3, 5, 7, 10, 25, 50]"
    (page) = "paginationHandler($event)">
  </mat-paginator>
</div>
<app-modal></app-modal>
