// client/client-react/src/shared/FilteredBook/index.tsx
import React from 'react';
import { Book } from '../../models/book.model';
import { connect } from 'react-redux';
import { UserService } from '../../service/users.service';
import { BookService } from '../../service/books.service';
import { UserInfoService } from '../../service/user-info.service';
import queryString from 'query-string';
import { User } from '../../models/user.model';
import { BookComponent } from '../BookComponent';
import Filter from './../Filter';
import { setBook } from '../../store/actions/filteredBookAction';

class FilteredBook extends React.Component<any, any>{
  constructor(props: any) {
    super(props);

    this.state = {
      books: []
    }

    this.userInfoService = new UserInfoService()
    this.userService = new UserService();
    this.bookService = new BookService();
  }

  public userInfoService: UserInfoService;
  public userService: UserService;
  public bookService: BookService;

  // componentDidMount() {
  //   this.getSomeBooks()
  // }


  public getSomeBooks(): void {
    const linkParams = queryString.parse(this.props.location.search);
    const data = {
      'authors[]': linkParams.authors as string[] || [],
      'categories[]': linkParams.categories as string[] || [],
      title: linkParams.title as string || '',
      pagination: {
        pageIndex: 0,
        pageSize: 5,
        length: 5,
        previousPageIndex: 0
      }
    };
    let favoritesId: string | string[] = [];
    this.bookService.getSomeBooks(data)
    .then((el: any) => {
      this.userService.getUser((this.userInfoService.getCurrentUser() as User).id as string)
      .then((user: User) => {
        favoritesId = user.books as string[];
        const listOfBook = el[0].listOfItem.map((book: Book) => {
            return {
              ...book,
              inFavorite: (favoritesId as string[]).indexOf(book._id as string) === -1 ? false : true
            };
          })

        this.props.setBook(listOfBook)
        data.pagination.length = el[0].totalCount[0].count;
      });
    });
  }

  render() {
    return (
      <div className="row">
        <Filter
          {...this.props.history}
          getSomeBooks={this.getSomeBooks.bind(this)}
        />
        <div className="col s10">
          {this.props.books.length > 0 ?
            this.props.books.map((book: Book, index: number) => {
              return (
                <BookComponent
                  key={index}
                  book={book}
                  buttonStatus={{
                    editeBtn: true,
                    deleteBtn: true,
                    ddToDbBtn: false,
                    addToFavoriteBtn: true
                  }}
                />)
            })
            : <h1>nothing</h1>}
        </div>
      </ div>
    )
  }
}

const mapStateToProps = (state: any) => {
  return {
    ...state.filteredBookReducer
  }
};

const mapDispatchToProps = (dispatch: any) => {
  return {
    setBook: (list: Book[]) => dispatch(setBook(list))
  }
};

export default connect(mapStateToProps, mapDispatchToProps)(FilteredBook)

// client/client-angular/src/app/shared/filtered-book/filtered-book.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { BookService } from 'src/app/service/books.service';
import { Book } from 'src/app/models/book.model';
import { UserService } from 'src/app/service/users.service';
import { UserInfo } from 'src/app/service/user-info.service';
import { Pagination } from 'src/app/models/pagination.model';

@Component({
  selector: 'app-filtered-book',
  templateUrl: './filtered-book.component.html',
  styleUrls: ['./filtered-book.component.scss']
})
export class FilteredBookComponent implements OnInit {
  public data;
  public books: Book[];
  public favoritesId: string[];

  constructor(
    private activeRoute: ActivatedRoute,
    private userInfo: UserInfo,
    private userService: UserService,
    private bookService: BookService,
    private router: Router
  ) {}

  ngOnInit() {
    const linkParams = this.activeRoute.snapshot.queryParams;
    this.data = {
      'authors[]': linkParams.authors,
      'categories[]': linkParams.categories,
      title: linkParams.title,
      pagination: {
        pageIndex: 0,
        pageSize: 5,
        length: 0,
        previousPageIndex: 0
      }
    };
    this.getSomeBooks();
  }

  public getSomeBooks() {
    this.bookService.getSomeBooks(this.data)
    .then((el: any) => {
      this.userService.getUser(this.userInfo.getCurrentUser().id)
      .then(user => {
        this.favoritesId = user.books;
      })
      .then(() => {
        this.books = el[0].books.map(book => {
          return {
            ...book,
            inFavorite: this.favoritesId.indexOf(book._id) === -1 ? false : true
          };
        });
        this.data.pagination.length = el[0].totalCount[0].count;
      });
    });
  }

  public paginationHandler(pageEvent) {
    this.data.pagination = pageEvent;
    this.getSomeBooks();
    return pageEvent;
  }

  show(pageEvent) {
    this.data.pagination = pageEvent;
    this.getSomeBooks();
    return pageEvent;
  }

  public getBooks(): void {
    this.bookService.getAllBooks(this.data.pagination)
    .then((el: any) => {
      this.userService.getUser(this.userInfo.getCurrentUser().id)
      .then(user => {
        this.favoritesId = user.books;
      })
      .then(() => {
        this.books = el.books.map(book => {
          return {
            ...book,
            inFavorite: this.favoritesId.indexOf(book._id) === -1 ? false : true
          };
        });
        this.data.pagination.length = el.totalCount[0].count;
      });
    });
  }

  public getFilteredBooks(data): void {
    this.router.navigate(
      ['/filtered'],
      {
        queryParams: data
      }
    )
    .then(() => {
      this.ngOnInit();
    });
  }
}

<div class="row">
  <app-filter
  [getAllBooks]="getSomeBooks.bind(this)"
  [getFilteredBooks]="getFilteredBooks.bind(this)"
  ></app-filter>
  <div class="col s10">
    <app-book
    *ngFor="let book of books"
    [book]="book"
    [buttonStatus]="{
      editeBtn: true,
      deleteBtn: true,
      ddToDbBtn: false,
      addToFavoriteBtn: true
    }"
    [reloadPage]="this.getSomeBooks.bind(this)"
    ></app-book>
    <mat-paginator 
      [length] = "this.data.pagination.length"
      [pageSize] = "this.data.pagination.pageSize"
      [pageSizeOptions] = "[3, 5, 7, 10, 25, 50]"
      (page) = "show($event)">
    </mat-paginator>
  </div>
</div>
