// client/client-angular/src/app/shared/book/book.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Book } from 'src/app/models/book.model';
import { UserInfo } from 'src/app/service/user-info.service';
import { BookService } from 'src/app/service/books.service';
import { MatDialog } from '@angular/material/dialog';
import { BookEditeModalComponent } from './book-edite-modal/book-edite-modal.component';
import { BookDeleteModalComponent } from './book-delete-modal/book-delete-modal.component';
import { AddBookModalComponent } from './book-add-modal/add-book-modal.component';
import { UserService } from 'src/app/service/users.service';
import { BookDeleteFromFavModalComponent } from './book-delete-from-fav-modal/book-delete-from-fav-modal.component';

@Component({
  selector: 'app-book',
  templateUrl: './book.component.html',
  styleUrls: ['./book.component.scss']
})
export class BookComponent implements OnInit {
  @Input() book: Book;
  @Input() buttonStatus: {
    editeBtn: boolean,
    deleteBtn: boolean,
    addToDbBtn: boolean,
    addToFavoriteBtn: boolean
  };
  @Input() reloadPage: () => void;

  public bookImage: string | ArrayBuffer;
  public bookExistInFavorites: boolean;

  constructor(
    public userInfo: UserInfo,
    public bookService: BookService,
    public userService: UserService,
    public dialog: MatDialog
  ) {
    this.bookImage = '';
  }

  ngOnInit() {
    this.bookImage = this.book.imageLinks ? this.book.imageLinks.thumbnail : this.book.image;
  }

  public addBookToFavorite(book: Book): void {
    this.userService.addBookToProfile(book);
    this.confirmDialog();
  }

  public addBookToDB(book: Book): void {
    this.book.inFavorite = true;

    const newBook: Book = {
      title: book.title,
      authors: book.authors,
      categories: book.categories || [],
      description: book.description,
      image: book.imageLinks.thumbnail || '',
      pageCount: book.pageCount,
      printType: book.printType,
      industryIdentifiers: book.industryIdentifiers
    };
    this.bookService.addBookToDB(newBook);
  }

  public deleteBook(book: Book): void {
    this.bookService.deleteBook(book)
    .then(() => {
      this.reloadPage();
    });
  }

  public chooseEditeBook(book): void {
    this.dialog.open(BookEditeModalComponent, {
      data: {
        book,
        reloadPage: this.reloadPage
      }
    });
  }

  public deleteDialog(book: Book): void {
    this.dialog.open(BookDeleteModalComponent, {
      data: {
        book,
        deleteBook: this.deleteBook.bind(this),
        reloadPage: this.reloadPage
      }
    });
  }

  public confirmDialog(): void {
    this.dialog.open(AddBookModalComponent, {
      data: {
        book: this.book,
        reloadPage: this.reloadPage
      }
    });
  }

  public deleteFromFavorites(): void {
    this.dialog.open(BookDeleteFromFavModalComponent, {
      data: {
        book: this.book,
        reloadPage: this.reloadPage
      }
    });
  }
}

<div class="z-depth-4">
  <div class="card horizontal">
    <div class="card-image">
      <img alt="Book image" src="{{bookImage}}" class="book-image">
      <button
        (click)="chooseEditeBook(book)"
        class="btn edite-btn rework-btn"
        *ngIf="buttonStatus.editeBtn">
        <i class="material-icons">edite</i>
      </button>
      <button 
        (click)="deleteDialog(book)"
        class="btn delete-btn rework-btn"
        *ngIf="buttonStatus.editeBtn">
        <i class="material-icons">delete</i>
      </button>
    </div>
    <div class="card-stacked">
      <div class="card-content">
        <div class="card-title">
          <b>{{book.title}}</b>
        </div>     
        <b *ngIf="book.categories_list || book.categories">Categories: </b>
          <span class="chip" *ngFor="let category of book.categories_list || book.categories">
            {{category.name || category}}<br>
          </span>
        <br>
        <b *ngIf="book.authors_list || book.authors">Authors: </b>
        <span class="chip" *ngFor="let author of book.authors_list || book.authors">
          {{author.name || author}}
        </span>
        <p class="book-description"><span *ngIf="book.description"><b>Description</b>:</span> {{book.description}}</p>
        <p><b>Pages: </b>{{book.pageCount}}</p>
      </div> 
      <div class="card-action">
        
        <button
          *ngIf="buttonStatus.addToFavoriteBtn  && !book.inFavorite"
          class="btn green add-to-pro-btn"
          (click)="addBookToFavorite(book)"
        >
        add to 'My favorites'
        </button>
        <button
          *ngIf="buttonStatus.addToFavoriteBtn && book.inFavorite"
          class="btn red add-to-pro-btn"
          (click)="deleteFromFavorites(book)"
        >
        delete from 'My favorites'
        </button>

        <button
          *ngIf="buttonStatus.addToDbBtn"
          class="btn add-to-pro-btn"
          [disabled]="book.alreadyExistInBD"
          (click)="addBookToDB(book)"
        >
        add to DB
        </button>
      </div>
    </div>
  </div>
</div>

// client/client-react/src/shared/BookComponent/index.tsx
import { FunctionComponent } from "react";
import React from "react";
import './style.scss'
import { Book } from "../../models/book.model";
import { CategoryAuthor } from './../../models/category-author.model';
interface BookProps {
  book: Book;
  buttonStatus: {
    editeBtn: boolean,
    deleteBtn: boolean,
    ddToDbBtn: boolean,
    addToFavoriteBtn: boolean
  }
}

export const BookComponent: FunctionComponent<BookProps> = ({book, buttonStatus}) => {
  const bookCategories: CategoryAuthor[] = book.categories_list as CategoryAuthor[];

  return (
    <div className="z-depth-4">
      <div className="card horizontal">
        <div className="card-image">
          <img alt="Bookimage" src={book.image as string} className="book-image" />
          {
            buttonStatus.editeBtn ?
            <button
              // (click)="chooseEditeBook(book)"
              className="btn edite-btn rework-btn"
              >
              <i className="material-icons">edite</i>
            </button>
            : null
          }
          {
            buttonStatus.editeBtn ?
            <button 
            // (click)="deleteDialog(book)"
            className="btn delete-btn rework-btn"
            >
              <i className="material-icons">delete</i>
            </button>
            : null
          }
        </div>
        <div className="card-stacked">
          <div className="card-content">
            <div className="card-title">
              <b>{book.title}</b>
            </div>
            {
              (book.categories_list as CategoryAuthor[]).length ?
              <>
                <b>Categories: </b>
                {bookCategories.map((category: CategoryAuthor, index: number) => {
                return (
                  <span key={index}>{category.name}</span>
                )
                })}
              </>
              : null
            }
            <br />
            {
              book.authors_list as CategoryAuthor[] ?
              <>
                <b>Author: </b>
                {(book.authors_list as CategoryAuthor[]).map((author: CategoryAuthor, index: number) => {
                return (
                  <span key={index}>{author.name}</span>
                )
                })}
              </>
              : null
            }
            <p className="book-description"><span // *ngIf="book.description"
            ><b>Description</b>:</span> {book.description}</p>
            <p><b>Pages: </b>{book.pageCount}</p>
          </div> 
          <div className="card-action">
            
            <button
              //*ngIf="buttonStatus.addToFavoriteBtn  && !book.inFavorite"
              className="btn green add-to-pro-btn"
              // (click)="addBookToFavorite(book)"
            >
            add to 'My favorites'
            </button>
            <button
              // *ngIf="buttonStatus.addToFavoriteBtn && book.inFavorite"
              className="btn red add-to-pro-btn"
              // (click)="deleteFromFavorites(book)"
            >
            delete from 'My favorites'
            </button>

            <button
              //*ngIf="buttonStatus.addToDbBtn"
              className="btn add-to-pro-btn"
              // [disabled]="book.alreadyExistInBD"
              // (click)="addBookToDB(book)"
            >
            add to DB
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
