// client/client-angular/src/app/components/filtered-book/filtered-book.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { BookService } from 'src/app/services/books.service';
import { Book } from 'src/app/models/book.model';
import { UserService } from 'src/app/services/users.service';
import { UserInfo } from 'src/app/services/user-info.service';
import { PaginationEvent } from 'src/app/models/pagination-event.model';
import { User } from 'src/app/models/user.model';

@Component({
  selector: 'app-filtered-book',
  templateUrl: './filtered-book.component.html',
  styleUrls: ['./filtered-book.component.scss']
})
export class FilteredBookComponent implements OnInit {
  public data: {
    'authors[]': string[],
    'categories[]': string[],
    title: string,
    pagination: PaginationEvent

  };
  public books: Book[];
  public favoritesId: string[];

  constructor(
    private activeRoute: ActivatedRoute,
    private userInfo: UserInfo,
    private userService: UserService,
    private bookService: BookService,
    private router: Router
  ) {}

  ngOnInit() {
    const linkParams = this.activeRoute.snapshot.queryParams;

    this.data = {
      'authors[]': linkParams.authors,
      'categories[]': linkParams.categories,
      title: linkParams.title,
      pagination: {
        pageIndex: 0,
        pageSize: 5,
        length: 0,
        previousPageIndex: 0
      }
    };
    this.getSomeBooks();
  }

  public async getSomeBooks(): Promise<void> {
    const el = await this.bookService.getSomeBooks(this.data);
    this.favoritesId = await this.userService.getUserFavoriteBooks();

    this.books = el[0].listOfItem.map((book: Book) => {
      return {
        ...book,
        inFavorite: this.favoritesId.indexOf(book._id) === -1 ? false : true
      };
    });
    if (el[0].totalCount[0]) {
      this.data.pagination.length = el[0].totalCount[0].count;
    }

  }

  public paginationHandler(pageEvent: PaginationEvent): PaginationEvent {
    this.data.pagination = pageEvent;
    this.getSomeBooks();
    return pageEvent;
  }

  public getFilteredBooks(data): void {
    // for changing link
    this.router.navigate(
      ['/filtered'],
      {
        queryParams: data
      }
    )
    .then(() => {
      this.ngOnInit();
    });
  }
}

<div class="row">
  <app-filter
  [getAllBooks]="getSomeBooks.bind(this)"
  [getFilteredBooks]="getFilteredBooks.bind(this)"
  ></app-filter>
  <div class="col s10">
    <h3 class="center"
    *ngIf="books === undefined || books.length === 0"
    >No overlap</h3>
    <app-book
    *ngFor="let book of books"
    [book]="book"
    [buttonStatus]="{
      editeBtn: true,
      deleteBtn: true,
      ddToDbBtn: false,
      addToFavoriteBtn: true
    }"
    [reloadPage]="this.getSomeBooks.bind(this)"
    ></app-book>
    <mat-paginator 
      [length] = "this.data.pagination.length"
      [pageSize] = "this.data.pagination.pageSize"
      [pageSizeOptions] = "[3, 5, 7, 10, 25, 50]"
      (page) = "paginationHandler($event)">
    </mat-paginator>
  </div>
</div>
<app-modal></app-modal>

// client/client-react/src/component/FilteredBook/filteredBook.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Book } from '../../models/book.model';
import UserService, { UserServiceClass } from '../../service/users.service';
import BookService, { BookServiceClass } from '../../service/books.service';
import UserInfoService, { UserInfo } from '../../service/user-info.service';
import { BookComponent } from '../../shared/BookComponent/BookComponent';
import Filter from '../../shared/FilterComponent/FilterComponent';
import * as actions from '../../store/actions/filteredBookAction';
import { PaginationEvent } from '../../models/pagination-event.model';
import PaginationComponent from '../../shared/PaginationComponent/pagination';
import './style.scss';
import { History } from 'history';
import { Store } from '../../store/store';
import { FilteredBooksState } from '../../store/reducers/filteredBooksReducer';

interface Props {
  history: History;
  store: FilteredBooksState;
  editeBook: (book: Book) => void;
  deleteBook: (book: Book) => void;
  bookToFromFavorites: (book: Book) => void;
  getSomeBooks: (searchString: string, pagination: PaginationEvent) => void;
}

interface State {
  pagination: PaginationEvent;
  searchQuery: string;
}

class FilteredBook extends React.Component<Props, State>{
  public userInfoService: UserInfo;
  public userService: UserServiceClass;
  public bookService: BookServiceClass;

  constructor(props: Props) {
    super(props);

    this.state = {
      pagination: {
        pageIndex: 0,
        pageSize: 10,
        length: 0
      },
      searchQuery: ''
    }

    this.userInfoService = UserInfoService;
    this.userService = UserService;
    this.bookService = BookService;

    this.addBookToFavorite = this.addBookToFavorite.bind(this);
    this.deleteBookFromDB = this.deleteBookFromDB.bind(this);
    this.editeBook = this.editeBook.bind(this);
  }

  componentDidMount() {
    this.getSomeBooks()
  }
  
  public async getSomeBooks(): Promise<void> {
    const searchQuery = this.props.history.location.search;
    await this.setState({
      searchQuery
    });
    await this.props.getSomeBooks(searchQuery, this.state.pagination);
  }
  
  public deleteBookFromDB(book: Book): void {
    this.props.deleteBook(book)
    this.getSomeBooks();
  }

  public addBookToFavorite(book: Book): void {
    this.props.bookToFromFavorites(book);
  }

  public async editeBook(book: Book): Promise<void>{
    await this.props.editeBook(book);
    await this.props.getSomeBooks(this.props.history.location.search, this.state.pagination);
  }

  render() {
    return (
      <div className="row">
        <Filter
          history={this.props.history}
          getSomeBooks={this.getSomeBooks.bind(this)}
        />
        <div className="col s10 filteredBookContent">
          {this.props.store.books.length > 0 ?
            this.props.store.books.map((book: Book, index: number) => {
              return (
                <BookComponent
                  key={index}
                  book={book}
                  buttonStatus={{
                    editeBtn: true,
                    deleteBtn: true,
                    ddToDbBtn: false,
                    addToFavoriteBtn: true
                  }}
                  deleteFromDB={this.deleteBookFromDB}
                  addToFavorite={this.addBookToFavorite}
                  editeBook={this.editeBook}
                  addBookToDB={() => {}}
                />)
            })
            : <h1>No overlap...</h1>}
            <PaginationComponent
              pagination={this.state.pagination}
              onPageSizeChange={(pageSize: number) => {
                this.setState({
                  pagination: {
                    ...this.state.pagination,
                    pageSize
                  }
                }, this.componentDidMount)
              }}
              callback={(current, pageSize) => {
                this.setState({
                  pagination: {
                    ...this.state.pagination,
                    pageIndex: current - 1,
                    pageSize
                  }
                }, this.getSomeBooks)
              }}
            />
        </div>
      </ div>
    )
  }
}

const mapStateToProps = (state: Store) => {
  return {
    store: {...state.filteredBook}
  }
};

const mapDispatchToProps = (dispatch: any) => {
  return {
    editeBook: (book: Book) => {
      dispatch(actions.editeBook(book));
    },
    deleteBook: (book: Book) => {
      dispatch(actions.deleteBook(book))
    },
    bookToFromFavorites: (book: Book) => {
      dispatch(actions.addDelBookFromFavorite(book))
    },
    getSomeBooks: (searchString: string, pagination: PaginationEvent) => {
      dispatch(actions.getSomeBooks(searchString, pagination))
    }
  }
};

export default connect(mapStateToProps, mapDispatchToProps)(FilteredBook)
