// client/client-react/src/Admin/UserManager/userManager.tsx
import React, { Props } from 'react';
import { UserService } from '../../service/users.service'
import { UserComponent } from '../../shared/UserComponent'
import { User } from '../../models/user.model'
import './style.scss';
import { setUserAtPage } from '../../store/actions/userManagerAction';
import { connect } from 'react-redux';

class UserManager extends React.Component<any, any> {
  constructor(props: Props<any>) {
    super(props);
    this.userService = new UserService();

    this.deleteUserFromDB = this.deleteUserFromDB.bind(this);
    this.editeUserInBD = this.editeUserInBD.bind(this);
    this.addNewUser = this.addNewUser.bind(this);
  }

  componentDidMount() {
    this.userService.getAllUsers({pageIndex: 0, pageSize: 5})
    .then(data => {
      this.props.setUsers(data[0].listOfItem)
    })
  }
  
  public userService: UserService;

  public deleteUserFromDB(user: User) {
    this.userService.delete(user._id)
    .then(() => {
      alert('successfuly deleted');
      this.componentDidMount();
    })
  }

  public editeUserInBD(user: User) {
    this.userService.edit(user._id, user)
    .then(() => {
      alert('Changed');
      this.componentDidMount();
    })
  }

  public addNewUser(user: User) {
    this.userService.registrate(user)
    .then(() => {
      alert('New user added')
    })
  }

  render() {
    return (
      <div className="container">
        <div className="input-field center">
        {/* [(ngModel)]="searchString" (ngModelChange)="this.onSearchStringChange.next($event)" */}
          <input type="text" name="searchField"/>
          <label htmlFor="searchField">Enter e-mail</label>
          <br/>
        </div>
      { this.props.usersAtPage ?
        this.props.usersAtPage.map((user: User, index: number) => { 
          return <UserComponent
          key={index}
          user={user}
          deleteUser={this.deleteUserFromDB}
          editeUser={this.editeUserInBD}
          addNewUser={this.addNewUser}
          />
        })
        : null
      }
       <div className="container center">
          <button
          className="btn orange center"
          // (click)="openDialog()"
          >Add new user</button>
        </div>
        {/* // <mat-paginator 
        //     [length] = "paginationParams.length"
        //     [pageSize] = "paginationParams.pageSize"
        //     [pageSizeOptions] = "[3, 5, 7, 10, 25, 50]"
        //     (page) = "paginationHandler($event)">
        // </mat-paginator> */}
      </div>
    )
  }
}

const mapStateToProps = (state: any) => {
  return {
    ...state.userManagerReducer
  }
};

const mapDispatchToProps = (dispatch: any) => {
  return {
    setUsers: (list: User[]): User[] => dispatch(setUserAtPage(list))
  }
};

export default connect(mapStateToProps, mapDispatchToProps)(UserManager)

// client/client-angular/src/app/admin/user-manager/user-manager.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { UserService } from 'src/app/service/users.service';
import { UserFormAddEditeModalComponent } from './user-forms-add-adite-modal/user-forms-add-adite-modal.component';
import { MatDialog } from '@angular/material/dialog';
import { UserDeleteModalComponent } from './user-delete-modal/user-delete-modal.component';
import { User } from 'src/app/models/user.model';

@Component({
  selector: 'app-user-manager',
  templateUrl: './user-manager.component.html',
  styleUrls: ['./user-manager.component.scss']
})
export class UserManagerComponent implements OnInit {

  constructor(
    private userService: UserService,
    public dialog: MatDialog
  ) { }

  users: object[];

  init(): void {
    this.userService.getAllUsers().then(el => {
      this.users = el.data.slice();
    });
  }

  deleteUser(id: string): void {
    this.userService.delete(id)
    .then(res => {
      this.init();
    });
  }

  openDialog(user: User): void {
    const dialogRef = this.dialog.open(UserFormAddEditeModalComponent, {
      data: {
        user,
        reloadPage:  this.init
      }
    });

    dialogRef.afterClosed().subscribe(result => {
    });
  }

  confirmDialog(userId: string, userName: string): void {
    const confirmDialog = this.dialog.open(UserDeleteModalComponent, {
      data: {
        userId,
        userName,
        deleteFunc: this.deleteUser.bind(this)
      }
    });

    confirmDialog.afterClosed().subscribe(result => {
    });
  }

  ngOnInit(): void {
    this.init();
  }
}

<div class="container">
    <div class="input-field center">
        <input type="text" name="searchField" [(ngModel)]="searchString" (ngModelChange)="this.onSearchStringChange.next($event)">
        <label for="searchField"
        [ngClass]="{active: searchString}"
        >Enter e-mail</label>
        <br>
    </div>
</div>
<div class="row">
    <div class="col s8 offset-s2">
        <div class="card horizontal z-depth-4" *ngFor="let user of users">
            <div class="card-image col s4">
                <img src="{{user.image || 'https://cdn.dribbble.com/users/219762/screenshots/2351573/saitama.png'}}" class="user-image">
                <button 
                (click)="openDialog(user)"
                class="btn edite-btn rework-btn">
                    <i class="material-icons">edite</i>
                </button>
                <button 
                (click)="confirmDialog(user._id, user.email)"
                class="btn delete-btn rework-btn">
                    <i class="material-icons">delete</i>
                </button>
            </div>
            <div class="card-stacked col s8">
                <div class="card-content">
                    <div class="card-title">
                        <b>{{user.name}}</b>
                        <br>
                        <span><small>({{(user.role === 1) ? 'admin' : 'user'}})</small></span>
                    </div>
                    <p><b>E-mail: </b>{{user.email}}</p>
                    <ul> 
                        <span><b>List of books:</b></span>
                        <li *ngFor="let book of user.book_list">{{book.title}}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container center">
    <button class="btn orange center" (click)="openDialog()">Add new user</button>
</div>
<mat-paginator 
    [length] = "paginationParams.length"
    [pageSize] = "paginationParams.pageSize"
    [pageSizeOptions] = "[3, 5, 7, 10, 25, 50]"
    (page) = "paginationHandler($event)">
</mat-paginator>
