// client/client-react/src/Admin/UserManager/index.tsx
import React, { Props } from 'react';
import { UserService } from './../../service/users.service'
import { UserComponent } from './../../shared/UserComponent'
import { User } from './../../models/user.model'
import './style.scss';

export class UserManager extends React.Component {
  constructor(props: Props<any>) {
    super(props);
    this.userService = new UserService();

    this.state = {
      title: 'book manager',
      userList: []
    }

    this.userService.getAllUsers({pageIndex: 0, pageSize: 5})
    .then(data => {
      console.log(data[0].listOfItem);
      this.setState({
        ...this.state,
        userList: data[0].listOfItem
      })
      return data.listOfItem;
    })
  }

  public userService: UserService;

  render() {
    return (
      <div className="container">
        <div className="input-field center">
        {/* [(ngModel)]="searchString" (ngModelChange)="this.onSearchStringChange.next($event)" */}
          <input type="text" name="searchField"/>
          <label htmlFor="searchField">Enter e-mail</label>
          <br/>
        </div>
      { (this.state as any).userList.map((user: User, index: number) => { 
        return <UserComponent
        key={index}
        user={user}
        />
      })}
       <div className="container center">
            <button
            className="btn orange center"
            // (click)="openDialog()"
            >Add new user</button>
        </div>
        {/* // <mat-paginator 
        //     [length] = "paginationParams.length"
        //     [pageSize] = "paginationParams.pageSize"
        //     [pageSizeOptions] = "[3, 5, 7, 10, 25, 50]"
        //     (page) = "paginationHandler($event)">
        // </mat-paginator> */}
      </div>
    )
  }
}

// client/client-angular/src/app/admin/user-manager/user-manager.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { UserService } from '../../service/users.service';
import { UserFormAddEditeModalComponent } from './user-forms-add-edite-modal/user-forms-add-edite-modal.component';
import { MatDialog } from '@angular/material/dialog';
import { UserDeleteModalComponent } from './user-delete-modal/user-delete-modal.component';
import { User } from '../../models/user.model';
import { Pagination } from 'src/app/models/pagination.model';

@Component({
  selector: 'app-user-manager',
  templateUrl: './user-manager.component.html',
  styleUrls: ['./user-manager.component.scss']
})
export class UserManagerComponent implements OnInit {
  public users: object[];
  public searchString: string;
  public paginationParams: Pagination = {
    pageIndex: 0,
    pageSize: 5,
    previousPageIndex: 0,
    length: 0
  };

  constructor(
    private userService: UserService,
    public dialog: MatDialog
  ) { }

  ngOnInit(): void {
    this.init();
  }

  public init(): void {
    this.userService.getAllUsers(this.paginationParams)
    .then(data => {
      this.users = data[0].users;
      this.paginationParams.length = data[0].totalCount[0].count;
    });
  }

  public deleteUser(id: string): void {
    this.userService.delete(id)
    .then(res => {
      this.init();
    });
  }

  public openDialog(user: User): void {
    const dialogRef = this.dialog.open(UserFormAddEditeModalComponent, {
      data: {
        user,
        reloadPage:  this.init.bind(this)
      }
    });

    dialogRef.afterClosed().subscribe(result => {
    });
  }

  public confirmDialog(userId: string, userEmail: string): void {
    const confirmDialog = this.dialog.open(UserDeleteModalComponent, {
      data: {
        userId,
        userEmail,
        deleteFunc: this.deleteUser.bind(this)
      }
    });

    confirmDialog.afterClosed().subscribe(result => {
    });
  }

  public userSearch(pagination: Pagination = {pageSize: this.paginationParams.pageSize, pageIndex: 0, }) {
    this.userService.getSomeUsers(this.searchString, pagination)
    .then(data => {
      console.log(data);
      this.users = data[0].users;
      this.paginationParams.length = data[0].totalCount[0].count;
    });
  }

 public paginationHandler(pageEvent) {
    if (this.searchString && this.searchString.length) {
      this.userSearch(pageEvent);
      return pageEvent;
    }
    this.paginationParams = pageEvent;
    this.init();
    return pageEvent;
  }
}

<div class="container">
    <div class="input-field center">
        <input type="text" name="searchField" [(ngModel)]="searchString" (ngModelChange)="this.onSearchStringChange.next($event)">
        <label for="searchField"
        [ngClass]="{active: searchString}"
        >Enter e-mail</label>
        <br>
    </div>
</div>
<div class="row">
    <div class="col s8 offset-s2">
        <div class="card horizontal z-depth-4" *ngFor="let user of users">
            <div class="card-image col s4">
                <img src="{{user.image || 'https://cdn.dribbble.com/users/219762/screenshots/2351573/saitama.png'}}" class="user-image">
                <button 
                (click)="openDialog(user)"
                class="btn edite-btn rework-btn">
                    <i class="material-icons">edite</i>
                </button>
                <button 
                (click)="confirmDialog(user._id, user.email)"
                class="btn delete-btn rework-btn">
                    <i class="material-icons">delete</i>
                </button>
            </div>
            <div class="card-stacked col s8">
                <div class="card-content">
                    <div class="card-title">
                        <b>{{user.name}}</b>
                        <br>
                        <span><small>({{(user.role === 1) ? 'admin' : 'user'}})</small></span>
                    </div>
                    <p><b>E-mail: </b>{{user.email}}</p>
                    <ul> 
                        <span><b>List of books:</b></span>
                        <li *ngFor="let book of user.book_list">{{book.title}}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container center">
    <button class="btn orange center" (click)="openDialog()">Add new user</button>
</div>
<mat-paginator 
    [length] = "paginationParams.length"
    [pageSize] = "paginationParams.pageSize"
    [pageSizeOptions] = "[3, 5, 7, 10, 25, 50]"
    (page) = "paginationHandler($event)">
</mat-paginator>
