// client/client-react/src/shared/Favorites/favoritesDeleteModal/favoritesDeleteModal.tsx
import React from 'react';
import { Book } from '../../../models/book.model';

interface Props {
  book: Book[];
  close: (bookId: string) => void;
  delete: (bookId: string) => void;
}

export default function FavoritesDeleteModal(props: Props) {
  return (
    <div>
      <p>Delete book: <b>"{props.book[0].title}"</b>from favorites?</p>
      <button
        className="btn green"
        onClick={() => props.close('')}
      >
        CLose
      </button>
      <button
        className="btn red"
        onClick={() => {
          props.close('');
          props.delete(props.book[0]._id as string)
        }}
      >
        Delete
      </button>
    </div>
  )
}

// client/client-angular/src/app/shared/favorites/favorite-delete-modal/favorites-delete-modal.component.ts
import { Component, Inject } from '@angular/core';
import { MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog';
import { Book } from 'src/app/models/book.model';
import { User } from 'src/app/models/user.model';

@Component({
  selector: 'app-favorites-delete-modal',
  templateUrl: './favorites-delete-modal.component.html',
  styleUrls: ['./favorites-delete-modal.component.scss']
})
export class FavoritesDeleteModalComponent {
  public user: User = this.data.user;
  constructor(
    public dialogRef: MatDialogRef<FavoritesDeleteModalComponent>,
    @Inject(MAT_DIALOG_DATA) public data: {
      book: Book,
      allBooks: Book[],
      user: User,
      delete: (user: User) => void
    }
  ) {}

  onNoClick(): void {
    this.dialogRef.close();
  }

  public deleteBook() {
    const restOfBook = [];
    this.data.allBooks.forEach((book: Book) => {
      if (book._id !== this.data.book._id) {
        restOfBook.push(book._id);
      }
    });
    this.user.books = restOfBook;
    this.data.delete(this.user);
    this.dialogRef.close();
  }
}

<h3>Delete book ?<br><b>"{{this.data.book.title}}"</b></h3>

<div class="containter center">
  <button class="btn green"
  [mat-dialog-close]
  >Cancel</button>
  <button class="btn red"
  (click)="deleteBook()"
  >Delete</button>
</div>
