// client/client-angular/src/app/shared/catalog/catalog.component.ts
import { Component, OnInit } from '@angular/core';
import { GoogleBooks } from '../../service/google-books.service';
import { BookService } from '../../service/books.service';
import { UserInfo } from '../../service/user-info.service';
import { Book } from 'src/app/models/book.model';
import { User } from 'src/app/models/user.model';

@Component({
  selector: 'app-catalog',
  templateUrl: './catalog.component.html',
  styleUrls: ['./catalog.component.scss']
})
export class CatalogComponent implements OnInit {

  public searchString: string;
  public listOfBook: any = this.googleBooks.getPageInfo().currentItems;
  public currentPage: number = this.googleBooks.getPageInfo().currentPage;

  constructor(
    private googleBooks: GoogleBooks,
    private booksService: BookService,
    private userInfo: UserInfo // use in template
    ) { }

  ngOnInit() {
  }

  public searchForBook(searchString: string, configForBookReq: {startIndex: number, maxResults: number}) {
    this.googleBooks.searchForBook(searchString, configForBookReq);
    this.currentPage  = configForBookReq.startIndex;
  }

  public changePage(page: number) {
    this.searchForBook( this.searchString, {startIndex: page * 10, maxResults: 10});
    this.currentPage = page;
  }
}

<div class="container">
    <div class="input-field">
        <input id="search" type="text" class="validate" [(ngModel)]="this.searchString">
        <label for="search" [ngClass]="{active: this.searchString}">Search field</label>
    </div>
    <button class="btn" (click)="searchForBook( this.searchString, {startIndex: 0, maxResults: 10})">GO</button>
    <app-book 
    *ngFor="let book of listOfBook"
    [book]="book"
    [buttonStatus]="{
        editeBtn: false,
        deleteBtn: false,
        addToFavoriteBtn: false,
        addToDbBtn: true
    }"
    ></app-book>
    <ul class="pagination">
        <li class="waves-effect"
            *ngFor="let page of this.googleBooks.getPageInfo().availablePages"
            [ngClass]="{active: (this.currentPage === page)}"
            (click)="this.changePage(page)"
            >
            <a routeLink="catalog">{{page + 1}}</a>
        </li>
    </ul>
</div>

// client/client-react/src/Catalog/Catalog.js
import React from 'react';
import Axios from 'axios';
import GoogleBook from '../components/GoogleBook/GoogleBook';

class Catalog extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      searchString: 'witcher',
      currentItems: [],
      availablePages: [],
      currentPage: 0,
      params: {
        startIndex: 0,
        maxResult: 10
      }
    };

    this.inputHandler = this.inputHandler.bind(this);
    this.buttonHandler = this.buttonHandler.bind(this);
    this.show = this.show.bind(this);
  };

  inputHandler(event) {
    this.setState({
      searchString: event.target.value
    });
  };

  buttonHandler() {
    const url = `https://www.googleapis.com/books/v1/volumes?q=${this.state.searchString}`;

    const params = this.state.params;
    const currentItems = [];
    let availablePages = [];  
    let currentPage;

    Axios.get(url, {params})
    .then(res => {
      res.data.items.forEach((element) => {
        currentItems.push(element.volumeInfo);
      });

      console.log('currentItems: ', currentItems)
      this.setState({
        currentItems
      })

      if (0 === params.startIndex) {
        const countPage = Math.ceil(res.data.totalItems / 20);

        for (let i = 0; i < countPage; i++) {
          availablePages.push(i);
        }
        console.log("availablePages: ", availablePages)
        this.setState({
          availablePages
        })

        currentPage = 0;
      }

      currentPage = params.startIndex / 10;

      this.setState({
        currentPage
      })
      console.log("STATE:", this.state)
      console.log('response: ', res)
      return res;
    })
    .catch(err => console.log(err));
  }

  show() {
    console.log(this.state)
  }

  render() {
    return (
      <div className="container">
        <div className="input-field">
          <input 
            id="search" 
            type="text" 
            className="validate"
            onChange={this.inputHandler}
          />
          <label htmlFor="search">Search field</label>
        </div>
        <button 
          className="btn"
          onClick={this.buttonHandler}
        >GO</button>
        <button 
          className="btn"
          onClick={this.show}
        >show</button>
        {/* *ngFor="let book of listOfBook" */}

        {(this.state.currentItems.length > 0) ?
          <GoogleBook book={this.state.currentItems[0]} />
          : null
        }

        
        <ul className="pagination">
          <li className="waves-effect"
            // *ngFor="let page of this.googleBooks.getPageInfo().availablePages"
            // [ngClass]="{active: (this.currentPage === page)}"
            // (click)="this.changePage(page)"
            >
            <a href="catalog">page + 1</a>
          </li>
        </ul>
      </div>
    )
  }
}

export default Catalog;
