// client/client-angular/src/app/auth-form/auth-form-login/auth-form-login.component.ts
import { Component } from '@angular/core';
import { UserService } from '../../service/users.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-auth-form-login',
  templateUrl: './auth-form-login.component.html',
  styleUrls: ['./auth-form-login.component.scss']
})

export class AuthFormLoginComponent {
  public user: {
    email: string,
    password: string
  };

  constructor(
    private userService: UserService,
    private route: Router
  ) {
    this.user = {
      email: '',
      password: ''
    };
  }

  public login(): void {
    this.userService.login(this.user)
    .then((data) => {
      this.route.navigate(['/profile']);
    })
    .catch(err => {
      alert('incorrect password or email');
    });
  }
}

<div class="row">
    <div class="col s4 offset-s4">
        <div class="input-field ">
            <input type="text" id="email" [(ngModel)]='user.email'>
            <label for="email" [ngClass]="{active: user.email}">E-mail</label>
        </div>
        <div class="input-field">
            <input type="password" id="password" [(ngModel)]='user.password'>
            <label for="password" [ngClass]="{active: user.password}">Password</label>
        </div>
        <button type="button" class="btn waves-effect" (click)="login()">Log in</button>
    </div>
</div>

// client/client-react/src/AuthForm/AuthFormLogin/AuthFormLogin.tsx
import React from 'react';
import Axios from 'axios';
// import UserService from '../../service/user.service';
import { UserForLoginReg } from '../../models/user.model';

class AuthFormlogin extends React.Component<{}, {user: UserForLoginReg}> {
  constructor(props: object) {
    super(props);

    this.state = {
      user: {
        email: '',
        password: ''
      }
    };

    this.handleInput = this.handleInput.bind(this);
    this.buttonHandler = this.buttonHandler.bind(this);
  }

  handleInput(event: React.ChangeEvent<HTMLInputElement>) {
    let data;
    switch (event.target.id) {
      case 'email': 
        data = {user: {email: event.target.value}};
        break;
      case 'password':
        data = {user: {password: event.target.value}};
        break;
      default:
        data = {user: {email: '', password: ''}};
    }
    this.setState(data)
  }

  buttonHandler() {
    console.log(this.state)
    Axios.post('http://localhost:3000/login', this.state)
      .then(res => {
        console.log(res)
          return res;
      })
      .catch(err => console.log(err));
  }

  render() {
    return (
      <div className="row">
        <div className="col s4 offset-s4">
          <div className="input-field ">
            <input 
              type="text" 
              id="email" 
              onChange={this.handleInput}
           />
            <label htmlFor="email">E-mail</label>
          </div>
          <div className="input-field">
            <input 
              type="password" 
              id="password" 
              onChange={this.handleInput} 
            />
            <label htmlFor="password">Password</label>
          </div>
          <button 
            type="button" 
            className="btn waves-effect"
            onClick={this.buttonHandler}
          >Log in</button>
        </div>
      </div>
    )
  }
}

export default AuthFormlogin;
